Repository UTSAVS26/PyVerse, pull requests merged in 2024-11, with the labels that each got.

#843 added machine learning project that detects handwritten texts
  Machine_Learning/Handwritten Text Recognition Model/README.md
  Machine_Learning/Handwritten Text Recognition Model/app.py
  Machine_Learning/Handwritten Text Recognition Model/requirements.txt
  Machine_Learning/Handwritten Text Recognition Model/results/OP1.png
  Machine_Learning/Handwritten Text Recognition Model/results/OP2.png
  Machine_Learning/Handwritten Text Recognition Model/results/OP3.png
  Machine_Learning/Handwritten Text Recognition Model/results/OP4.png
  Machine_Learning/Handwritten Text Recognition Model/results/OP5.png
  Machine_Learning/Handwritten Text Recognition Model/results/OP6.png
  Machine_Learning/Handwritten Text Recognition Model/results/OP7.png
  Project-Structure.md
Labels: Contributor, Status: Requested Changes, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#997 add BFS algo in trees section of data structures
  Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_BFS.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#999 Added Min Stack program
  Algorithms_and_Data_Structures/Stack/Min_Stack.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#994 Fixes Bacteria Classification
  Deep_Learning/Bacteria_Classification/Bacteria_Classification.ipynb
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext

#1005 Added Interactive Tower of Hanoi Game
  Game_Development/Tower of Hanoi/README.md
  Game_Development/Tower of Hanoi/game.py
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext

#1000 #992 Added Word Scramble Challenge Game
  Game_Development/Word Scramble Challenge/README.md
  Game_Development/Word Scramble Challenge/main.py
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext

#984 Added Economic Analysis using World Bank Data
  Data_Science/Economic Analysis/Global_EconoViz.py
  Data_Science/Economic Analysis/README.md
  Data_Science/Economic Analysis/economic_analysis_data.csv
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#1057 Lavenshtein distance algo added
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Hard-DP-Problems/levenshtein-distance.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#1035 ✅ : Cat & Dog CNN classifier model
  Image processing/Cat_Dog_CNN_classifier/Cat_Dog_CNN_classifier.ipynb
  Image processing/Cat_Dog_CNN_classifier/README.md
  Image processing/Cat_Dog_CNN_classifier/classification.h5
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext

#958 Added Strassen's Matrix Multiplication in divide and conquer
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Divide_and_Conquer/Strassen's_Matrix_Multiplication.py
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#1008 Tweet Classification Disaster Detection AI Fixes #1007
  Deep_Learning/Tweet_Classificaion_DL/Disaster Tweet Classification using NLP and Deep Learning.ipynb
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext

#545 added rat in a maze and kth permutation problem in backtracking folder
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/kth_permutation_sequence.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/rat_in_a_maze.py
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#1076 adding graph traversals
  Algorithms_and_Data_Structures/Graph/Menu_driven_code_BFS_Traversal.py
  Algorithms_and_Data_Structures/Graph/Menu_driven_code_DFS_Traversal.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#1077 Added the program of Adjacency Matrix
  Algorithms_and_Data_Structures/Graph/Adjacency_Matrix.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#1079 added remove duplicates from a sorted list #1062
  Algorithms_and_Data_Structures/Linked List/Remove_Duplicates_from_Sorted_List/program.py
  Algorithms_and_Data_Structures/Linked List/Remove_Duplicates_from_Sorted_List/readme.md
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#857 Added more Problems in Dynamic programming
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Basic-DP-Problems/Paint_House.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Basic-DP-Problems/SubSet_Sum.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Basic-DP-Problems/nth_tribonacci_num.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Basic-DP-Problems/zero_one_knapsack.py
  Project-Structure.md
Labels: Contributor, Status: Approved, WoB'24 (Winter of Blockchain), level1, gssoc-ext, hacktoberfest

#1094 Catalan Algo, Min Steps to One and Knapsack With Constraints Added
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Hard-DP-Problems/catalan-numbers.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Hard-DP-Problems/knapsack-with-constraints.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Hard-DP-Problems/min-steps-to-one.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#964 Added Study buddy
  Machine_Learning/AI-powered Study assistant python/app.py
  Machine_Learning/AI-powered Study assistant python/readme.md
  Machine_Learning/AI-powered Study assistant python/requirements.txt
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest

#967 Added Amazon product availbility checker
  Beginner_Projects/Amazon product availbility checker/amazon.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest

#1099 Create README.md
  Computer Vision/Object Size Detection/README.md
  Computer Vision/Object Size Detection/Results/res1.png
  Computer Vision/Object Size Detection/Results/res2.png
  Computer Vision/Object Size Detection/Results/res3.png
  Computer Vision/Object Size Detection/app.py
  Computer Vision/Object Size Detection/requirements.txt
  Project-Structure.md
Labels: Status: Approved

#1101 Cyber Threat Intelligence Dashboard
  Cybersecurity_Tools/Cyber Threat Intelligence Dashboard/Readme.md
  Cybersecurity_Tools/Cyber Threat Intelligence Dashboard/coding.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#1029 Feature: Added web application Image Resizer & Filters in image processing folder
  Image processing/image-resizer-filter-tool/README.md
  Image processing/image-resizer-filter-tool/app.py
  Image processing/image-resizer-filter-tool/index.html
  Image processing/image-resizer-filter-tool/script.js
  Image processing/image-resizer-filter-tool/style.css
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#1108 COVID Detection from CXR Using Explainable CNN
  Explainable-AI/Covid_Detection_from_Explainable_cnn/Readme.md
  Explainable-AI/Covid_Detection_from_Explainable_cnn/covid-detection-from-cxr-using-explainable-cnn.ipynb
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#1109 Explainable AI: Using Local Interpretable Model-agnostic Explanations (LIME) & SHapley Additive exPlanations (SHAP)
  Explainable-AI/Intro_to_LIME_and_Shap/Readme.md
  Explainable-AI/Intro_to_LIME_and_Shap/explainable-ai-intro-to-lime-shap.ipynb
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext

#1104 Added the AI-Powered Super-Resolution and Image Restoration model
  Image processing/AI Super-Resolution and Image Restoration/README.md
  Image processing/AI Super-Resolution and Image Restoration/main.py
  Project-Structure.md
Labels: Contributor, Status: Approved, Status: Ready to Merge, level1, gssoc-ext

#447 added 2048.py along with README.md in Game_Development
  Game_Development/2048/2048.py
  Game_Development/2048/README.md
Labels: Contributor, Status: Approved, Status: Ready to Merge, level1, gssoc-ext, hacktoberfest

#423 Added ATM Interface
  Beginner_Projects/ATM Interface/ATM.py
  Beginner_Projects/ATM Interface/README.md
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest

#551 House price prediction
  Machine_Learning/House_Price_Prediction/Readme.md
  Machine_Learning/House_Price_Prediction/RidgeModel.pkl
  Machine_Learning/House_Price_Prediction/cleaned_housedata.csv
  Machine_Learning/House_Price_Prediction/house_data_cleaning.py
  Machine_Learning/House_Price_Prediction/house_price_predicter.py
  Machine_Learning/House_Price_Prediction/housedata.csv
  Machine_Learning/House_Price_Prediction/requirements.txt
Labels: Contributor, Status: Approved, Status: Ready to Merge, level1, gssoc-ext, hacktoberfest

#1127 heart disease
  Machine_Learning/Distracted Driver Detection/Distrated Driver detection.ipynb
  Machine_Learning/Distracted Driver Detection/Input/driver.gif
  Machine_Learning/Distracted Driver Detection/README.md
  Machine_Learning/Heart Disease Prediction [END 2 END]/Heart Disease Prediction.ipynb
  Machine_Learning/Heart Disease Prediction [END 2 END]/README.md
  Machine_Learning/Heart Disease Prediction [END 2 END]/heart.csv
  Project-Structure.md
Labels: Contributor, Status: Approved, Status: Ready to Merge, level1, gssoc-ext, hacktoberfest

#1097 Added new project called as "Object Detector"
  Generative-AI/Object Detector/README.md
  Generative-AI/Object Detector/app.py
  Generative-AI/Object Detector/requirement.txt
Labels: Contributor, Status: Approved, Status: Ready to Merge, level1, gssoc-ext

#1105 IoT Device Control Script
  Automation_Tools/Iot_control/Readme.md
  Automation_Tools/Iot_control/iot_control.py
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, Pass : Other Mentor Review
