Repository UTSAVS26/PyVerse, pull requests merged in 2024-10, with the labels that each got.

#11 Linked Lists
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Circular_Doubly_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Circular_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Doubly_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Dynamic_Linear_Queue_using_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Dynamic_Stack_using_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Linear_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/README.md
Labels: invalid, Status: Requested Changes

#12 Add Update structure workflow
  .github/scripts/update_dir_structure.py
  .github/workflows/update-structure.yml
  .gitignore
  Data_Science/Data-science.md
  README.md
  repo_structure.txt
Labels: Contributor, Status: Approved, WoB'24 (Winter of Blockchain), Level2

#23 Added Stock App
  Beginner_Projects/Stock App/Readme.md
  Beginner_Projects/Stock App/Templates/base.html
  Beginner_Projects/Stock App/Templates/financials.html
  Beginner_Projects/Stock App/Templates/index.html
  Beginner_Projects/Stock App/server.py
Labels: documentation, Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#27 Morse Code Translator with GUI
  Beginner_Projects/Morse Code Translator with GUI/README.md
  Beginner_Projects/Morse Code Translator with GUI/main.py
  Beginner_Projects/Morse Code Translator with GUI/screenshots/tkinter-working.gif
  README.md
  repo_structure.txt
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest-accepted

#46 QR code generator
  Beginner_Projects/QR Generator/README.md
  Beginner_Projects/QR Generator/generate_qrcode.py
Labels: good first issue, Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#43 Twitter Sentiment Analysis
  Machine_Learning/Twitter Sentiment Analysis/README.md
  Machine_Learning/Twitter Sentiment Analysis/Twitter Sentiment Analysis.ipynb
  Machine_Learning/Twitter Sentiment Analysis/Twitter-sentiment-analysis-1.jpg
  Machine_Learning/Twitter Sentiment Analysis/images.jpg
  Machine_Learning/Twitter Sentiment Analysis/images/Input Data.jpg
  Machine_Learning/Twitter Sentiment Analysis/images/Model Performance.jpg
  Machine_Learning/Twitter Sentiment Analysis/images/Negative wordcloud.jpg
  Machine_Learning/Twitter Sentiment Analysis/images/Positive wordcloud.jpg
  Machine_Learning/Twitter Sentiment Analysis/images/Sentiment countplot.jpg
  Machine_Learning/Twitter Sentiment Analysis/images/sample.md
  Machine_Learning/Twitter Sentiment Analysis/train.csv
  Machine_Learning/Twitter Sentiment Analysis/twitter2-720x540.jpg
  README.md
  repo_structure.txt
Labels: good first issue, Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest-accepted

#39 Added documentation for Turtle module with code example
  Beginner_Projects/Turtle/Readme.md
  Beginner_Projects/Turtle/rainbow_spiral.py
  Beginner_Projects/Turtle/turtle_spiral.py
  README.md
  repo_structure.txt
Labels: Contributor, Status: Approved, WoB'24 (Winter of Blockchain), Level1

#55 added all the required files
  Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_Avl_Tree.py
  Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_Binary_Search_Tree.py
  Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_Binary_Tree.py
  Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_DFS.py
  Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_Tree_Traversals.py
  Algorithms_and_Data_Structures/Trees/README.md
Labels: Contributor, Status: Requested Changes, Level2, gssoc-ext, hacktoberfest

#77 Calculator app
  Beginner_Projects/Calculator_App/README.md
  Beginner_Projects/Calculator_App/main.py
Labels: good first issue, Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#80 bird_species_classification
  Deep_Learning/Bird Species Classification/Dataset/Readme.md
  Deep_Learning/Bird Species Classification/Images/InceptionV3.png
  Deep_Learning/Bird Species Classification/Images/inception_resnet_v2 .png
  Deep_Learning/Bird Species Classification/Images/masked_image_1.png
  Deep_Learning/Bird Species Classification/Images/masked_image_2.png
  Deep_Learning/Bird Species Classification/Images/masked_image_3.png
  Deep_Learning/Bird Species Classification/Model/bird_species_classification.ipynb
  Deep_Learning/Bird Species Classification/Readme.md
Labels: good first issue, Contributor, Status: Requested Changes, Level2, gssoc-ext, hacktoberfest

#78 Hand Gesture Vehicle Control
  Machine_Learning/Hand Game Controller/"A" Key Binding.png
  Machine_Learning/Hand Game Controller/"D" Key Binding.png
  Machine_Learning/Hand Game Controller/"S" Key Binding.png
  Machine_Learning/Hand Game Controller/"W" Key Binding.png
  Machine_Learning/Hand Game Controller/README.md
  Machine_Learning/Hand Game Controller/main-mobile-cam.py
  Machine_Learning/Hand Game Controller/main-pc-cam.py
  Machine_Learning/Hand Game Controller/requirements.txt
  README.md
  repo_structure.txt
Labels: good first issue, Contributor, Status: Assigned, Level2, gssoc-ext, hacktoberfest

#76 Time Series Visualization
  Data_Science/time_series_visualization/README.md
  Data_Science/time_series_visualization/Time_Series_Report.pdf
  Data_Science/time_series_visualization/Time_Series_Visualization.ipynb
  Data_Science/time_series_visualization/airline_passengers.csv
  Data_Science/time_series_visualization/autocorrelation_plot.png
  Data_Science/time_series_visualization/eda_plot.png
  Data_Science/time_series_visualization/exponential_smoothing_plot.png
  Data_Science/time_series_visualization/moving_average_plot.png
  Data_Science/time_series_visualization/seasonal_plot.png
  Data_Science/time_series_visualization/trend_analysis_plot.png
Labels: Contributor, Status: Requested Changes, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#92 Create turtle.py
  Beginner_Projects/Turtle/turtle.py
Labels: good first issue, Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#93 Addition of Design and Analysis of Algorithms
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/All_Pair_Shortest_path_problems/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/All_Pair_Shortest_path_problems/floyd_warshall.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/All_Pair_Shortest_path_problems/johnsons.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/graph_coloring.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/hamiltonian_cycle.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/knights_tour.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/maze_solving.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Backtracking/n_queens.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Branch_and_Bound/8_puzzle.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Branch_and_Bound/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Divide_and_Conquer/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Divide_and_Conquer/binary_search.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Divide_and_Conquer/merge_sort.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Divide_and_Conquer/min_max.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Divide_and_Conquer/quick_sort.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Divide_and_Conquer/tower_of_hanoi.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Dynammic_Programming/01_knapsack.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Dynammic_Programming/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Dynammic_Programming/lcs.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Dynammic_Programming/matrix_multiplication.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Dynammic_Programming/nth_fibonacci.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Graph_Traversing/BFS.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Graph_Traversing/DFS.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Graph_Traversing/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/activity_selection.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/fractional_knapsack.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/huffman_code.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/job_scheduling.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/optimal_merge_pattern.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/travel_salesman.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Maximum_Flow/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Maximum_Flow/ford_fulkenson.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Minimum_spanning_tree/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Minimum_spanning_tree/kruskal.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Minimum_spanning_tree/prim.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Single_Source_Shortest_path_problems/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Single_Source_Shortest_path_problems/bellman_ford.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Single_Source_Shortest_path_problems/dijkstra.py
Labels: Contributor, Status: Approved, Level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted, Star Contributor

#90 Deep_Learning/Spam Vs Ham Mail Classification
  Deep_Learning/Spam Vs Ham Mail Classification [With Streamlit GUI]/Model/app1.py
  Deep_Learning/Spam Vs Ham Mail Classification [With Streamlit GUI]/Model/model1.ipynb
  Deep_Learning/Spam Vs Ham Mail Classification [With Streamlit GUI]/Model/model1_(1) (1).ipynb
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#94 added code and dataset
  Machine_Learning/Multivitamine Prediction/multivitamins_data.csv
  Machine_Learning/Multivitamine Prediction/scrape.py
Labels: good first issue, Contributor, Level2, gssoc-ext, hacktoberfest

#110 feat : password generator
  Beginner_Projects/Password-Generator/README.md
  Beginner_Projects/Password-Generator/passwordGenerator.py
  Beginner_Projects/Password-Generator/requirements.txt
Labels: Contributor, Status: Approved, hacktoberfest, hacktoberfest-accepted

#117 Addition of Image tool to Automation Tools
  Automation_Tools/Image-Tool/Image_Tool.py
  Automation_Tools/Image-Tool/README.md
  Automation_Tools/Image-Tool/requirements.txt
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#122 Diagrams or Graphics
  PyVerse - Skill Selection.pdf
  PyVerse - Skill Selection_page-0001.jpg
  README.md
Labels: documentation, enhancement, Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#95 Create Tasker.py
  Beginner_Projects/Tasker.py
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#149 feat : barcode generator
  Beginner_Projects/Bar-Code-Generator/README.md
  Beginner_Projects/Bar-Code-Generator/barCodeGenerator.py
  Beginner_Projects/Bar-Code-Generator/requirements.txt
Labels: Contributor, Status: Approved, hacktoberfest, hacktoberfest-accepted

#82 Chess
  Algorithms_and_Data_Structures/BinarySearchTree/__init__.py
  Algorithms_and_Data_Structures/BinarySearchTree/__pycache__/bst.cpython-312.pyc
  Algorithms_and_Data_Structures/BinarySearchTree/__pycache__/bstnode.cpython-312.pyc
  Algorithms_and_Data_Structures/BinarySearchTree/bst.py
  Algorithms_and_Data_Structures/BinarySearchTree/bstnode.py
  Algorithms_and_Data_Structures/BinarySearchTree/main.py
  Beginner_Projects/chess_game/.gitignore
  Beginner_Projects/chess_game/__init__.py
  Beginner_Projects/chess_game/board.py
  Beginner_Projects/chess_game/game.py
  Beginner_Projects/chess_game/piece.py
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#202 Added some projects and enhances some code and improved the documenta…
  Advanced_Projects/GUI Based TaskManager/mang.py
  Advanced_Projects/GUI Based TaskManager/readme.md
  Beginner_Projects/Bar-Code-Generator/README.md
  Beginner_Projects/Bar-Code-Generator/barCodeGenerator.py
  Beginner_Projects/Budget-tracker/budget.md
  Beginner_Projects/Budget-tracker/budget.py
  Beginner_Projects/Calculator_App/main.py
  Beginner_Projects/Egg_Catcher_Game.py
Labels: Contributor, Status: Approved, Status: Assigned, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#206 added tabulation method in nth_fibo problem and memoization method in…
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Dynammic_Programming/lcs.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Dynammic_Programming/matrix_multiplication.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Dynammic_Programming/nth_fibonacci.py
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#216 Add Digital Clock using Python and Tkinter
  Beginner_Projects/Digital Clock/Digital Clock.PNG
  Beginner_Projects/Digital Clock/README.md
  Beginner_Projects/Digital Clock/digital_clock.py
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#220 Addition of N-Queen Visualiser in DSA Projects | Issue #181
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/N-Queen-Visualiser-main/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/N-Queen-Visualiser-main/chess.js
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/N-Queen-Visualiser-main/index.css
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/N-Queen-Visualiser-main/index.html
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#229 added recursion files
  Algorithms_and_Data_Structures/Pattern Search/aho_corasick.py
  Algorithms_and_Data_Structures/Pattern Search/bitap_algorithm.py
  Algorithms_and_Data_Structures/Pattern Search/boyer_moore.py
  Algorithms_and_Data_Structures/Pattern Search/kmp_pattern_search.py
  Algorithms_and_Data_Structures/Pattern Search/naive_pattern_search.py
  Algorithms_and_Data_Structures/Pattern Search/rabin_karp.py
  Algorithms_and_Data_Structures/Pattern Search/suffix_array.py
  Algorithms_and_Data_Structures/Recurssion/Binary_Search.py
  Algorithms_and_Data_Structures/Recurssion/Check_for_Palindrome.py
  Algorithms_and_Data_Structures/Recurssion/Count_Vowels_in_a_String.py
  Algorithms_and_Data_Structures/Recurssion/Factorial.py
  Algorithms_and_Data_Structures/Recurssion/Fibonacci_Series.py
  Algorithms_and_Data_Structures/Recurssion/Power_Function.py
  Algorithms_and_Data_Structures/Recurssion/Reverse_a_String.py
  Algorithms_and_Data_Structures/Recurssion/TowerofHanoi.py
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#231 Customer Segmentation and Statistical Analysis Enhancements
  Data_Science/customer_segmentation/Customer_Segmentation.ipynb
  Data_Science/customer_segmentation/Mall_Customers.csv
  Data_Science/customer_segmentation/README.md
  Data_Science/customer_segmentation/age_distribution.png
  Data_Science/customer_segmentation/age_group_counts.png
  Data_Science/customer_segmentation/boxplot_spending_score.png
  Data_Science/customer_segmentation/customer_segmentation_2D.png
  Data_Science/customer_segmentation/customer_segmentation_3D.png
  Data_Science/customer_segmentation/customer_segmentation_statistical_analysis_report.pdf
  Data_Science/customer_segmentation/gender_distribution.png
  Data_Science/customer_segmentation/income_vs_spending_score.png
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#233 Added a new Project un Cybersecurity Tools | Pixel_Decoder issue #198.
  Cybersecurity_Tools/Pixel_Decoder/pixel_decoder.py
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#224 Add URL shorter
  Beginner_Projects/URL_Shortener/README.md
  Beginner_Projects/URL_Shortener/url_shortener.py
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#168 Added File Locking Mechanism with OpenCV
  Deep_Learning/File-Locking-Mechanism/Face_Recognition_Script/Face recognition.py
  Deep_Learning/File-Locking-Mechanism/Face_Recognition_Script/FaceDetection.py
  Deep_Learning/File-Locking-Mechanism/Face_Recognition_Script/haarcascade_frontalface_alt.xml
  Deep_Learning/File-Locking-Mechanism/Face_Recognition_Script/lbpcascade_frontalface.xml
  Deep_Learning/File-Locking-Mechanism/README.md
  Deep_Learning/File-Locking-Mechanism/locker.bat
  Deep_Learning/File-Locking-Mechanism/requirements.txt
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#234 #201 Added Number Guessing Game
  Game_Development/Number Guessing Game/README.md
  Game_Development/Number Guessing Game/main.py
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#236 Added Snake Game (Issue: #226)
  Game_Development/Snake_Game/README.md
  Game_Development/Snake_Game/Snake.py
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#230 Added AVL Tree Visualizer project
  Algorithms_and_Data_Structures/avl_tree_visualizer/.gitignore
  Algorithms_and_Data_Structures/avl_tree_visualizer/README.md
  Algorithms_and_Data_Structures/avl_tree_visualizer/input.txt
  Algorithms_and_Data_Structures/avl_tree_visualizer/main.py
  Algorithms_and_Data_Structures/avl_tree_visualizer/output.txt
  Algorithms_and_Data_Structures/avl_tree_visualizer/requirements.txt
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#256 Added an encryption and decryption app
  Beginner_Projects/Number Guessing Game/README.md
  Beginner_Projects/Web Scraper/README.md
  Cybersecurity_Tools/Encryption_Decryption app/README.md
  Cybersecurity_Tools/Encryption_Decryption app/encrypt_decrypt.py
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#253 Added Research Snap
  Advanced_Projects/Research-Snap/.env-sample
  Advanced_Projects/Research-Snap/README.md
  Advanced_Projects/Research-Snap/app.py
  Advanced_Projects/Research-Snap/requirements.txt
Labels: Contributor, Status: Ready to Merge, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#248 Added Real time chat application
  Beginner_Projects/Chat App/README.md
  Beginner_Projects/Chat App/chat_client.py
  Beginner_Projects/Chat App/chat_server.py
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#246 Added Sudoku Solver
  Beginner_Projects/Sudoku Solver/README.md
  Beginner_Projects/Sudoku Solver/sudoku.py
Labels: Contributor, Status: Approved, Level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#238 Add A* algorithm
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Single_Source_Shortest_path_problems/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Single_Source_Shortest_path_problems/a_star.py
Labels: Contributor, Status: Approved, Level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#194 Added GPS-Free Navigational Chatbot
  Advanced_Projects/NaviBot-Voice-Assistant/README.md
  Advanced_Projects/NaviBot-Voice-Assistant/app.py
  Advanced_Projects/NaviBot-Voice-Assistant/main.py
  Advanced_Projects/NaviBot-Voice-Assistant/map.py
  Advanced_Projects/NaviBot-Voice-Assistant/requirements.txt
Labels: Contributor, Status: Requested Changes, Level3, gssoc-ext, hacktoberfest

#228 Added project "Autofill Personal Info Using Adhaar Card Image" under automation category.
  Automation_Tools/Autofill personal info using Aadhar Card Image/OCR ADHAAR API/app.py
  Automation_Tools/Autofill personal info using Aadhar Card Image/README.md
  Automation_Tools/Autofill personal info using Aadhar Card Image/RESULT.md
  Automation_Tools/Autofill personal info using Aadhar Card Image/assets/images/Output.png
  Automation_Tools/Autofill personal info using Aadhar Card Image/assets/images/api_response.png
  Automation_Tools/Autofill personal info using Aadhar Card Image/assets/images/easyocr.png
  Automation_Tools/Autofill personal info using Aadhar Card Image/assets/images/tesseract.png
  Automation_Tools/Autofill personal info using Aadhar Card Image/extract_aadhar_details.ipynb
  Automation_Tools/Autofill personal info using Aadhar Card Image/requirements.txt
  Repo-structure.md
  repo_structure.txt
Labels: Contributor, Status: Requested Changes, Level2, gssoc-ext, hacktoberfest

#274 Create Repeated_Dijkstra.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/All_Pair_Shortest_path_problems/Repeated_Dijkstra.py
Labels: Contributor, Status: Approved, hacktoberfest, hacktoberfest-accepted

#331 Adding Video Forensics Analysis Tool
  Cybersecurity_Tools/VidForensicsTool/LICENSE
  Cybersecurity_Tools/VidForensicsTool/README.md
  Cybersecurity_Tools/VidForensicsTool/main.py
  Cybersecurity_Tools/VidForensicsTool/requirements.txt
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#286 Added Medicine Prediction System ML Model to Machine Learning
  Machine_Learning/WeCare/README.md
  Machine_Learning/WeCare/datasets/README.md
  Machine_Learning/WeCare/datasets/Symptom-severity.csv
  Machine_Learning/WeCare/datasets/Training.csv
  Machine_Learning/WeCare/datasets/description.csv
  Machine_Learning/WeCare/datasets/diets.csv
  Machine_Learning/WeCare/datasets/medications.csv
  Machine_Learning/WeCare/datasets/precautions_df.csv
  Machine_Learning/WeCare/datasets/svc.pkl
  Machine_Learning/WeCare/datasets/symtoms_df.csv
  Machine_Learning/WeCare/datasets/train_mdl.ipynb
  Machine_Learning/WeCare/datasets/workout_df.csv
  Machine_Learning/WeCare/instance/README.md
  Machine_Learning/WeCare/instance/database.db
  Machine_Learning/WeCare/main.py
  Machine_Learning/WeCare/models/svc.pkl
  Machine_Learning/WeCare/static/bg-image.jpg
  Machine_Learning/WeCare/static/healthcare.jpg
  Machine_Learning/WeCare/static/home-bgimg.jpg
  Machine_Learning/WeCare/static/logo.jpg
  Machine_Learning/WeCare/templates/about.html
  Machine_Learning/WeCare/templates/blog.html
  Machine_Learning/WeCare/templates/contact.html
  Machine_Learning/WeCare/templates/dashboard.html
  Machine_Learning/WeCare/templates/diagnosis.html
  Machine_Learning/WeCare/templates/footer.html
  Machine_Learning/WeCare/templates/index.html
  Machine_Learning/WeCare/templates/layout.html
  Machine_Learning/WeCare/templates/login.html
  Machine_Learning/WeCare/templates/profile.html
  Machine_Learning/WeCare/templates/register.html
Labels: Contributor, Status: Requested Changes, level2, gssoc-ext, hacktoberfest

#310 Sugarcane Leaf Disease Detection
  Deep_Learning/Sugarcane Disease Prediction/Dataset/readme.md
  Deep_Learning/Sugarcane Disease Prediction/Images/classification_report.png
  Deep_Learning/Sugarcane Disease Prediction/Images/confusion_matrix.png
  Deep_Learning/Sugarcane Disease Prediction/Images/input.png
  Deep_Learning/Sugarcane Disease Prediction/Images/vgg16_graph.png
  Deep_Learning/Sugarcane Disease Prediction/models/ensemble_model.ipynb
  Deep_Learning/Sugarcane Disease Prediction/readme.md
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#311 Movie data Visualization #282
  DataVizLearnig/Movie Data Visualization/MovieRatings.xlsx
  DataVizLearnig/Movie Data Visualization/Readme.md
  DataVizLearnig/Movie Data Visualization/maincode.py
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#318 📃: Added TextToTalk - A text to speech project
  Machine_Learning/TextToTalk/LICENSE
  Machine_Learning/TextToTalk/README.md
  Machine_Learning/TextToTalk/requirements.txt
  Machine_Learning/TextToTalk/scripts/ExtText.py
  Machine_Learning/TextToTalk/scripts/Pipeline.py
  Machine_Learning/TextToTalk/scripts/TTS.py
  Machine_Learning/TextToTalk/scripts/app.py
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#319 Adding a new Feature Using Computer Vision (Media Pipe) to Detect Bad…
  Deep_Learning/Detect Bad Posture Media Pipe/Media_Pipe_Pose_checkpoint.ipynb
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#325 Added BMI Calculator
  Beginner_Projects/BMI Calculator/BMI.py
  Beginner_Projects/BMI Calculator/README.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#329 Spoken Language Translator
  Deep_Learning/Spoken Language Translator/README.MD
  Deep_Learning/Spoken Language Translator/main.py
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#343 Addition of 2 New Projects in Web Dev | Issue #269
  Web_Development/Password_Generator--main/assets/copy.svg
  Web_Development/Password_Generator--main/index.css
  Web_Development/Password_Generator--main/index.html
  Web_Development/Password_Generator--main/index.js
  Web_Development/Recursive-Tic-Tac-Toe-main.zip
  Web_Development/Recursive-Tic-Tac-Toe-main/.DS_Store
  Web_Development/Recursive-Tic-Tac-Toe-main/.vscode/settings.json
  Web_Development/Recursive-Tic-Tac-Toe-main/assets/favicon.ico
  Web_Development/Recursive-Tic-Tac-Toe-main/assets/gradient-bg.jpg
  Web_Development/Recursive-Tic-Tac-Toe-main/index.html
  Web_Development/Recursive-Tic-Tac-Toe-main/index.js
  Web_Development/Recursive-Tic-Tac-Toe-main/styles.css
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#347 feat: Added Web Scrapping project
  Automation_Tools/Web Scrapping/README.md
  Automation_Tools/Web Scrapping/WebScrapping.ipynb
  Automation_Tools/Web Scrapping/books_data.csv
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#350 Feat: Landmark Detection Model
  Machine_Learning/Landmark_Detection/README.md
  Machine_Learning/Landmark_Detection/app.py
  Machine_Learning/Landmark_Detection/images/image1.jpeg
  Machine_Learning/Landmark_Detection/images/image2.jpeg
  Machine_Learning/Landmark_Detection/images/image3.jpeg
  Machine_Learning/Landmark_Detection/images/image4.jpeg
  Machine_Learning/Landmark_Detection/images/image5.jpeg
  Machine_Learning/Landmark_Detection/landmark-detection-tfhub.ipynb
  Machine_Learning/Landmark_Detection/requirements.txt
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#353 Online video editor
  Video Processing/Online Video Editor/Readme.md
  Video Processing/Online Video Editor/edits.py
  Video Processing/Online Video Editor/requirements.txt
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#355 Added Queue DS Problems
  Algorithms_and_Data_Structures/Queue/Circular_Queue.py
  Algorithms_and_Data_Structures/Queue/Deque.py
  Algorithms_and_Data_Structures/Queue/Linear_Queue.py
  Algorithms_and_Data_Structures/Queue/Priority_Queue.py
  Algorithms_and_Data_Structures/Queue/Queue_Using_Two_Stacks.py
  Algorithms_and_Data_Structures/Queue/README.md
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#368 implemented brute force attack to crack password
  Cybersecurity_Tools/bruteforce_password_cracking/main.py
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#380 Feat: CLI based Task Tracker written in python
  Beginner_Projects/Task-Tracker/README.md
  Beginner_Projects/Task-Tracker/requirements.txt
  Beginner_Projects/Task-Tracker/setup.py
  Beginner_Projects/Task-Tracker/task_tracker.egg-info/PKG-INFO
  Beginner_Projects/Task-Tracker/task_tracker.egg-info/SOURCES.txt
  Beginner_Projects/Task-Tracker/task_tracker.egg-info/dependency_links.txt
  Beginner_Projects/Task-Tracker/task_tracker.egg-info/entry_points.txt
  Beginner_Projects/Task-Tracker/task_tracker.egg-info/requires.txt
  Beginner_Projects/Task-Tracker/task_tracker.egg-info/top_level.txt
  Beginner_Projects/Task-Tracker/task_tracker/__init__.py
  Beginner_Projects/Task-Tracker/task_tracker/__pycache__/__init__.cpython-312.pyc
  Beginner_Projects/Task-Tracker/task_tracker/__pycache__/cli.cpython-312.pyc
  Beginner_Projects/Task-Tracker/task_tracker/cli.py
  Beginner_Projects/Task-Tracker/tasks.json
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#395 Added Red Wine Quality detection
  Machine_Learning/Red Wine Quality Detection/Readme.md
  Machine_Learning/Red Wine Quality Detection/Red_Wine_Quality (1).ipynb
  Machine_Learning/Red Wine Quality Detection/dataset.csv
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#432 SkillSync - Skill Gap Analysis for Career Growth and Course Recommendation
  Advanced_Projects/SkillSync/.env-sample
  Advanced_Projects/SkillSync/README.md
  Advanced_Projects/SkillSync/app.py
  Advanced_Projects/SkillSync/requirements.txt
  Advanced_Projects/SkillSync/templates/index.html
Labels: Status: Approved, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#393 HeapSort Visualizer And Time Complexity Analysis
  Algorithms_and_Data_Structures/HeapSort/heapsortvisualizer.py
  Algorithms_and_Data_Structures/HeapSort/timecomplexity1.py
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#384 Fix: Enhance Data Science guide
  Data_Science/Data-science.md
  Data_Science/Datasciecne-poster.jpg
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#387 Stock Price Prediction using Machine Learning
  Machine_Learning/Analying_ML_model_using_maang/README.md
  Machine_Learning/Analying_ML_model_using_maang/main.py
  Machine_Learning/Analying_ML_model_using_maang/requirements.txt
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#389 Added tic tac toe game
  Game_Development/Tic_Tac_Toe/README.md
  Game_Development/Tic_Tac_Toe/tic_tac_toe.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#392 Network packet analyzer
  Cybersecurity_Tools/Packet-sniffer/Readme.md
  Cybersecurity_Tools/Packet-sniffer/packetsniffer.py
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#434 Added EdgeLock-X: Trusted Execution and In-Memory ML Model Protection Framework for Face Authentication
  Advanced_Projects/EdgeLock-X/.env-sample
  Advanced_Projects/EdgeLock-X/README.md
  Advanced_Projects/EdgeLock-X/faces/Mysterio.png
  Advanced_Projects/EdgeLock-X/generate_keys.py
  Advanced_Projects/EdgeLock-X/requirements.txt
  Advanced_Projects/EdgeLock-X/static/app.js
  Advanced_Projects/EdgeLock-X/static/home.html
  Advanced_Projects/EdgeLock-X/static/index.html
  Advanced_Projects/EdgeLock-X/tee_server.py
  Advanced_Projects/EdgeLock-X/web_server.py
Labels: Status: Review Ongoing, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#446 added coin change and mst problem in greedy folder
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/Coin_change.py
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/README.md
  Algorithms_and_Data_Structures/Design_and_Analysis_of_Algorithms/Greedy_Techniques/minimum_spanning_tree.py
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#467 Added Data Summarizer NLP using Python
  Machine_Learning/Data Summarizer NLP/__pycache__/app.cpython-39.pyc
  Machine_Learning/Data Summarizer NLP/app.py
  Machine_Learning/Data Summarizer NLP/readme.md
  Machine_Learning/Data Summarizer NLP/requirements.txt
  Machine_Learning/Data Summarizer NLP/templates/index.html
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#512 Added a card game with multiple types and modes
  Game_Development/Card quest/Cards.py
  Game_Development/Card quest/Readme.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#441 Style Transfer with Neural Network
  Machine_Learning/Style Transfer with Neural Network/README.md
  Machine_Learning/Style Transfer with Neural Network/Style Transfer with Neural Networks.ipynb
  Machine_Learning/Style Transfer with Neural Network/content image.jpg
  Machine_Learning/Style Transfer with Neural Network/style image.jpg
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#509 Dice Rolling simulator
  Game_Development/Dice_rolling_simulator/README.md
  Game_Development/Dice_rolling_simulator/dice_1.png
  Game_Development/Dice_rolling_simulator/dice_2.png
  Game_Development/Dice_rolling_simulator/dice_3.png
  Game_Development/Dice_rolling_simulator/dice_4.png
  Game_Development/Dice_rolling_simulator/dice_5.png
  Game_Development/Dice_rolling_simulator/dice_6.png
  Game_Development/Dice_rolling_simulator/main3.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#523 Added Pig Dice Game
  Game_Development/Pig Dice Game/Readme.md
  Game_Development/Pig Dice Game/app.py
  Game_Development/Pig Dice Game/tempCodeRunnerFile.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#520 Add Bubble hit game
  Game_Development/Bubble Shoot/Readme.md
  Game_Development/Bubble Shoot/main.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#460 Implemented Apriori and Association Rule Mining for Intrusion Detection System.
  Machine_Learning/Intrusion Detection System/Dataset/Test_data.csv
  Machine_Learning/Intrusion Detection System/Dataset/Train_data.csv
  Machine_Learning/Intrusion Detection System/Image/output.png
  Machine_Learning/Intrusion Detection System/network-intrusion-detection-using-ARM.ipynb
  Machine_Learning/Intrusion Detection System/readme.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#530 Volume Control Using Hand Gesture
  Computer Vision/Volume Control Using Hand Gesture/.idea/.gitignore
  Computer Vision/Volume Control Using Hand Gesture/.idea/PyVerse.iml
  Computer Vision/Volume Control Using Hand Gesture/.idea/inspectionProfiles/Project_Default.xml
  Computer Vision/Volume Control Using Hand Gesture/.idea/inspectionProfiles/profiles_settings.xml
  Computer Vision/Volume Control Using Hand Gesture/.idea/misc.xml
  Computer Vision/Volume Control Using Hand Gesture/.idea/modules.xml
  Computer Vision/Volume Control Using Hand Gesture/.idea/vcs.xml
  Computer Vision/Volume Control Using Hand Gesture/GestureVolume.py
  Computer Vision/Volume Control Using Hand Gesture/HandTrackingModule.py
  Computer Vision/Volume Control Using Hand Gesture/README.md
  Computer Vision/Volume Control Using Hand Gesture/docs/Untitledvideo-MadewithClipchamp2-ezgif.com-video-to-gif-converter.gif
  Computer Vision/Volume Control Using Hand Gesture/docs/docs.md
  Computer Vision/Volume Control Using Hand Gesture/requirements.txt
Labels: Contributor, Status: Requested Changes, level1, gssoc-ext, hacktoberfest

#483 File Integrity Checker Feature Added in CyberSecurity Tools Category
  Cybersecurity_Tools/File Integrity Checker/ReadMe.md
  Cybersecurity_Tools/File Integrity Checker/file_integrity_checker.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#471 Added Basic Contact Manager to Beginner Projects
  Beginner_Projects/Contact_Manager
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#474 added sorting algorithms
  Algorithms_and_Data_Structures/sorting_algorithms/Bubble_Sort.py
  Algorithms_and_Data_Structures/sorting_algorithms/Counting_sort.py
  Algorithms_and_Data_Structures/sorting_algorithms/Heap_sort.py
  Algorithms_and_Data_Structures/sorting_algorithms/Insertion_Sort.py
  Algorithms_and_Data_Structures/sorting_algorithms/Merge_Sort.py
  Algorithms_and_Data_Structures/sorting_algorithms/Quick_sort.py
  Algorithms_and_Data_Structures/sorting_algorithms/Radix_Sort.py
  Algorithms_and_Data_Structures/sorting_algorithms/Selection_Sort
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#406 Animal identification
  Deep_Learning/Deep-learning-for-Animal-Identification/Identify the Animal_colab.ipynb
  Deep_Learning/Deep-learning-for-Animal-Identification/Identify_the_Animal_novalid_colab.ipynb
  Deep_Learning/Deep-learning-for-Animal-Identification/README.md
  Deep_Learning/Deep-learning-for-Animal-Identification/images/sub.jpg
  Deep_Learning/Deep-learning-for-Animal-Identification/subm01.csv
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#574 dp-basic-series
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Basic-DP-Problems/climbing-stairs.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Basic-DP-Problems/fibonacci-seq.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Basic-DP-Problems/house-robber.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#582 Cold Email Generator ISSUE: #554
  Generative-AI/Cold-Email-Generator/README.md
  Generative-AI/Cold-Email-Generator/app/.env
  Generative-AI/Cold-Email-Generator/app/app.py
  Generative-AI/Cold-Email-Generator/app/requirements.txt
  Generative-AI/Cold-Email-Generator/img/architecture.png
  Generative-AI/Cold-Email-Generator/img/img.png
  Generative-AI/Cold-Email-Generator/img/img1.png
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#585 Traffic Accident Prediction Model using Deep Learning
  Deep_Learning/Traffic Accident Prediction Model using Deep Learning/README.md
  Deep_Learning/Traffic Accident Prediction Model using Deep Learning/Traffic Accident Prediction Model using Deep Learning.ipynb
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#608 updated hungman game
  Game_Development/Hangman-main/hangman.py
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#557 Added diabetes predictor
  Machine_Learning/Diabetes-Prediction/Diabetes Predictor - Deployment.py
  Machine_Learning/Diabetes-Prediction/Procfile
  Machine_Learning/Diabetes-Prediction/README.md
  Machine_Learning/Diabetes-Prediction/app.py
  Machine_Learning/Diabetes-Prediction/diabetes-prediction-rfc-model.pkl
  Machine_Learning/Diabetes-Prediction/kaggle_diabetes.csv
  Machine_Learning/Diabetes-Prediction/readme_resources/application-error-heroku.png
  Machine_Learning/Diabetes-Prediction/requirements.txt
  Machine_Learning/Diabetes-Prediction/static/diabetes-favicon.ico
  Machine_Learning/Diabetes-Prediction/static/diabetes.webp
  Machine_Learning/Diabetes-Prediction/static/no-diabetes.webp
  Machine_Learning/Diabetes-Prediction/static/styles.css
  Machine_Learning/Diabetes-Prediction/templates/index.html
  Machine_Learning/Diabetes-Prediction/templates/result.html
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#518 Added Lowest Common Ancestor menu driven code
  Algorithms_and_Data_Structures/Trees/Menu_Driven_Code_for_Lowest_common_ancestor.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#418 Stock Prediction with CAPM and Fama-French Model
  Data_Science/stock_prediction/CAPM_FamaFrench.ipynb
  Data_Science/stock_prediction/README.md
  Data_Science/stock_prediction/output_1.png
  Data_Science/stock_prediction/output_10.png
  Data_Science/stock_prediction/output_11.png
  Data_Science/stock_prediction/output_12.png
  Data_Science/stock_prediction/output_2.png
  Data_Science/stock_prediction/output_3.png
  Data_Science/stock_prediction/output_4.png
  Data_Science/stock_prediction/output_5.png
  Data_Science/stock_prediction/output_6.png
  Data_Science/stock_prediction/output_7.png
  Data_Science/stock_prediction/output_8.png
  Data_Science/stock_prediction/output_9.png
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#659 #642 Improve Error Handling and User Feedback in TextToTalk Application.
  Machine_Learning/TextToTalk/scripts/ExtText.py
  Machine_Learning/TextToTalk/scripts/Pipeline.py
  Machine_Learning/TextToTalk/scripts/app.py
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#515 Web page phishing detection added in machine_learning
  Machine_Learning/Web Page Phishing Detection/README.md
  Machine_Learning/Web Page Phishing Detection/dataset_phishing.csv
  Machine_Learning/Web Page Phishing Detection/web_page_phishing_detection.ipynb
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#546 fixed issue #422
  Machine_Learning/SONAR_Rock_ Mine_Prediction/sonar.py
  Machine_Learning/SONAR_Rock_ Mine_Prediction/sonar_data.csv
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#687 Created a maze game
  Game_Development/Maze/Maze.py
  Game_Development/Maze/readme.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#455 Added Google Search Analysis with python
  Data Analysis/Google Search Analysis with python/Google_Search_Analysis_with_python.ipynb
  Data Analysis/Google Search Analysis with python/Readme.md
  Data Analysis/Google Search Analysis with python/barchart.png
  Data Analysis/Google Search Analysis with python/pie-plot.png
  Data Analysis/Google Search Analysis with python/scatter.png
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#692 Adding PingPong Game folder
  Game_Development/PingPong/Readme.md
  Game_Development/PingPong/main.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#413 Added a simple keylogger
  Cybersecurity_Tools/Keylogger/README.md
  Cybersecurity_Tools/Keylogger/keylogger.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#603 added beginner project-LABBOT
  Beginner_Projects/contents_lab.json
  Beginner_Projects/labbot.ipynb
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#657 added-medium-dp-problems
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Medium-DP-Problems/coin-change.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Medium-DP-Problems/longest-inc-subseq.py
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#685 Ml Project Add
  Machine_Learning/CreditCardFraudDetection/Fraud_Detection_Machine_Learning_Project.ipynb
  Machine_Learning/CreditCardFraudDetection/README.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#684 Anomaly-Based Intrusion Detection System
  Machine_Learning/Anomaly_based_ids/Anomaly_based_IDS.ipynb
  Machine_Learning/Anomaly_based_ids/README.md
  Machine_Learning/Anomaly_based_ids/saved_model/IDS_model_20241010-184208.h5
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#590 Add Financial AI Assistant
  Beginner_Projects/Financial AI Assistant/main.py
  Beginner_Projects/Financial AI Assistant/readme.md
Labels: Contributor, Status: Assigned, level1, gssoc-ext, hacktoberfest

#768 Implement Simple Blockchain in Python: Create and Validate Blocks
  Blockchain_Development/Basic Python Blockchain Implementation/blockchain_demo.py
  Blockchain_Development/Basic Python Blockchain Implementation/readme.md
Labels: Contributor, Status: Review Ongoing, WoB'24 (Winter of Blockchain), level2, gssoc-ext, hacktoberfest

#730 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#742 Added a phishing detection tool
  Cybersecurity_Tools/Phishing detection tool/README.md
  Cybersecurity_Tools/Phishing detection tool/phishing_detection.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#782 Create Auto-Label
  .github/workflows/auto-label.yml
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#764 more dp problems
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Medium-DP-Problems/partition-subset-sum.py
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Medium-DP-Problems/unique-paths.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#722 Added Sentiment-Analysis-Of-Restaurant-Reviews Issue #710
  Sentiment-Analysis-Of-Restaurant-Reviews/README.md
  Sentiment-Analysis-Of-Restaurant-Reviews/Restaurant_Reviews.tsv
  Sentiment-Analysis-Of-Restaurant-Reviews/Sentiment Analysis of Restaurant Reviews.ipynb
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#743 File encryption tool
  Cybersecurity_Tools/File_encryption_tool/Encryption.py
  Cybersecurity_Tools/File_encryption_tool/readme.md
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#792 Flask Blockchain application
  Blockchain_Development/Flask-Blockchain-app/.gitignore
  Blockchain_Development/Flask-Blockchain-app/LICENSE
  Blockchain_Development/Flask-Blockchain-app/Pipfile
  Blockchain_Development/Flask-Blockchain-app/Pipfile.lock
  Blockchain_Development/Flask-Blockchain-app/README.md
  Blockchain_Development/Flask-Blockchain-app/blockchain/__init__.py
  Blockchain_Development/Flask-Blockchain-app/blockchain/__main__.py
  Blockchain_Development/Flask-Blockchain-app/blockchain/app.py
  Blockchain_Development/Flask-Blockchain-app/blockchain/blockchain.py
  Blockchain_Development/Flask-Blockchain-app/blockchain/blockchain_structure.py
  Blockchain_Development/Flask-Blockchain-app/blockchain/static/css/custom.css
  Blockchain_Development/Flask-Blockchain-app/blockchain/templates/base.html
  Blockchain_Development/Flask-Blockchain-app/blockchain/templates/configure.html
  Blockchain_Development/Flask-Blockchain-app/blockchain/templates/index.html
  Blockchain_Development/Flask-Blockchain-app/client/__init__.py
  Blockchain_Development/Flask-Blockchain-app/client/__main__.py
  Blockchain_Development/Flask-Blockchain-app/client/app.py
  Blockchain_Development/Flask-Blockchain-app/client/static/css/custom.css
  Blockchain_Development/Flask-Blockchain-app/client/templates/base.html
  Blockchain_Development/Flask-Blockchain-app/client/templates/index.html
  Blockchain_Development/Flask-Blockchain-app/client/templates/make_transaction.html
  Blockchain_Development/Flask-Blockchain-app/client/templates/view_transactions.html
  Blockchain_Development/Flask-Blockchain-app/client/transaction.py
  Blockchain_Development/Flask-Blockchain-app/requirements.txt
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#808 🐛Bug Fix: Project structure text file
  .github/scripts/update_dir_structure.py
  .github/workflows/update-structure.yml
  Project-Structure.md
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#729 Pull Request addressing the Issue #709 to add Voice_Assistant Project.
  Beginner_Projects/Voice_Assistant/main.py
  Beginner_Projects/Voice_Assistant/musicLibrary.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#770 Initialize Network Packet Analyzer project
  Cybersecurity_Tools/Netwrok Packet Analyzer/packet_analyzer.py
  Cybersecurity_Tools/Netwrok Packet Analyzer/readme.md
Labels: Contributor, Status: Approved, WoB'24 (Winter of Blockchain), level1, gssoc-ext, hacktoberfest

#691 Interactive code playground
  Web_Development/interactive-code-playground/README.md
  Web_Development/interactive-code-playground/__pycache__/main.cpython-311.pyc
  Web_Development/interactive-code-playground/main.py
  Web_Development/interactive-code-playground/playground.db
  Web_Development/interactive-code-playground/static/index.html
  Web_Development/interactive-code-playground/temp_code.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#653 Want to add crossword game
  Game_Development/Crossword Game/crossword.py
  Game_Development/Crossword Game/readme.md
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#566 Spell Checker
  Beginner_Projects/Spell Checker/README.md
  Beginner_Projects/Spell Checker/spell_checker.py
  Beginner_Projects/Spell Checker/words.txt
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#664 Added pomodoro clock
  Beginner_Projects/pomodoro_Clock/README.md
  Beginner_Projects/pomodoro_Clock/img.jpg
  Beginner_Projects/pomodoro_Clock/main.py
Labels: Contributor, Status: Approved, hacktoberfest, hacktoberfest-accepted

#398 Explainable AI Techniques
  Explainable-AI/Explainable AI Research Methods/Readme.md
  Explainable-AI/Explainable AI Research Methods/xai.ipynb
Labels: Contributor, Status: Review Ongoing, level2, gssoc-ext, hacktoberfest

#834 Fixed bugs & improved the code of QR_GUI app
  Beginner_Projects/QR Generator/QR_code_generator_GUI.py
Labels: Contributor, Status: Approved, level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#836 🧑‍💻Enhanced the BST implementation
  Algorithms_and_Data_Structures/BinarySearchTree/bst.py
  Algorithms_and_Data_Structures/BinarySearchTree/bstnode.py
  Algorithms_and_Data_Structures/BinarySearchTree/main.py
  Algorithms_and_Data_Structures/BinarySearchTree/tree_exceptions.py
Labels: Contributor, Status: Approved, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#831 added three algorithms in DSA folder
  Algorithms_and_Data_Structures/bellman_ford/Bellman_ford.py
  Algorithms_and_Data_Structures/closest_pair_of_points/closest_pair_of_points.py
  Algorithms_and_Data_Structures/graham_scan/convex_hull_graham_scan.py
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest

#420 Count the number of zeroes#414
  Algorithms_and_Data_Structures/Recurssion/Countnumberofzeroes.py
  Machine_Learning/Sentiment Analysis/__pycache__/code.cpython-311.pyc
  Machine_Learning/Sentiment Analysis/code.py
  Machine_Learning/Sentiment Analysis/performance_metrics.png
  Machine_Learning/Sentiment Analysis/test.csv
  performance_metrics.png
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#765 (#757) Allow Users to Manually Edit the Generated Email in Cold Email Generator App
  Generative-AI/Cold-Email-Generator/app/app.py
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest

#676 Add ARP Spoofing Detection Tool with GUI and Real-Time Monitoring
  Cybersecurity_Tools/ARP Spoofing Detection Tool/Readme.md
  Cybersecurity_Tools/ARP Spoofing Detection Tool/arp_spoofing_detection.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#858 Added TextSummarization Model, Continuation to PR #785
  Project-Structure.md
  Web_Development/Test_Sumarrization_NLP/README.md
  Web_Development/Test_Sumarrization_NLP/textsummary.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#829 Added a time complexity checker
  Algorithms_and_Data_Structures/TimeComplexity_analyzer/Checker.py
  Algorithms_and_Data_Structures/TimeComplexity_analyzer/README.md
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#784 Plagiarism checker Python
  Advanced_Projects/Plagiarism-checker/app.py
  Advanced_Projects/Plagiarism-checker/fatma.txt
  Advanced_Projects/Plagiarism-checker/image.png
  Advanced_Projects/Plagiarism-checker/john.txt
  Advanced_Projects/Plagiarism-checker/juma.txt
  Advanced_Projects/Plagiarism-checker/pictures/become_a_patron_button.png
  Advanced_Projects/Plagiarism-checker/requirements.txt
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#577 [Code Addition Request]: Credit Card Fraud Detection
  Machine_Learning/Credit Card Fraud Detection/Credit_card_fraud_detection.ipynb
  Machine_Learning/Credit Card Fraud Detection/Readme.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#818 Tim Sort sorting algorithm added
  Algorithms_and_Data_Structures/SearchingAlgorithms/JumpSearch.py
  Algorithms_and_Data_Structures/sorting_algorithms/Tim_Sort.py
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#840 adde the catch the fsalling fruits
  Game_Development/Catch_The_Fruit/Catch_the_fruit.py
  Game_Development/Catch_The_Fruit/images/basket.jpg
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#813 Added a web application firewall
  Cybersecurity_Tools/Web Application Firewall/README.md
  Cybersecurity_Tools/Web Application Firewall/waf.py
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#832 #774 Added the Word Ladder Puzzle Game
  Game_Development/Word Ladder Puzzle Game/README.md
  Game_Development/Word Ladder Puzzle Game/main.py
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#443 Fixed : Custom Auto-Labeling Workflow for GitHub
  .github/workflows/auto-label.yml
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#853 Added multistage-graph in dynamic programming
  Algorithms_and_Data_Structures/Dynamic-Programming-Series/Medium-DP-Problems/multistage-graph.py
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#872 Image Caption Generation with Audio Outputs (Issue #869)
  Deep_Learning/Image Caption Generation with Audio Output/README.md
  Deep_Learning/Image Caption Generation with Audio Output/app.py
  Deep_Learning/Image Caption Generation with Audio Output/requirements.txt
  Deep_Learning/Image Caption Generation with Audio Output/static/ignore
  Deep_Learning/Image Caption Generation with Audio Output/templates/index.html
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#876 Added excel to CSV converter.
  Beginner_Projects/Excel to CSV/Readme.md
  Beginner_Projects/Excel to CSV/excelToCsv.py
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#940 Sentiment analysis using machine learning
  Machine_Learning/Sentiment Analysis using machine learning/code.py
  Machine_Learning/Sentiment Analysis using machine learning/performance_metrics.png
  Machine_Learning/Sentiment Analysis using machine learning/test.csv
  Machine_Learning/Sentiment Analysis/__pycache__/code.cpython-311.pyc
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest

#948 Added a ML model to analyze plant leaves using CNN
  Machine_Learning/Leaf disease analyzer using ML/Model_Training.ipynb
  Machine_Learning/Leaf disease analyzer using ML/README.md
  Machine_Learning/Leaf disease analyzer using ML/ab.md
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap-grid.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap-grid.css.map
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap-grid.min.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap-grid.min.css.map
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap-reboot.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap-reboot.css.map
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap-reboot.min.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap-reboot.min.css.map
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap.css.map
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap.min.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/bootstrap.min.css.map
  Machine_Learning/Leaf disease analyzer using ML/static/css/font-awesome.min.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/main.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/normalize.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/style.css
  Machine_Learning/Leaf disease analyzer using ML/static/css/test.css
  Machine_Learning/Leaf disease analyzer using ML/static/js/bootstrap.bundle.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/bootstrap.bundle.js.map
  Machine_Learning/Leaf disease analyzer using ML/static/js/bootstrap.bundle.min.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/bootstrap.bundle.min.js.map
  Machine_Learning/Leaf disease analyzer using ML/static/js/bootstrap.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/bootstrap.js.map
  Machine_Learning/Leaf disease analyzer using ML/static/js/bootstrap.min.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/bootstrap.min.js.map
  Machine_Learning/Leaf disease analyzer using ML/static/js/jquery.min.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/main.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/newjs.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/plugins.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/vendor/jquery-1.12.0.min.js
  Machine_Learning/Leaf disease analyzer using ML/static/js/vendor/modernizr-2.8.3.min.js
  Machine_Learning/Leaf disease analyzer using ML/templates/import.html
  Machine_Learning/Leaf disease analyzer using ML/templates/index.html
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#942 GAN-based Art Generator
  Deep_Learning/GAN-based Art Generator using Deep learning/Dataset/README.md
  Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image 1.png
  Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image 2.png
  Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image 3.png
  Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image 4.png
  Deep_Learning/GAN-based Art Generator using Deep learning/Model/GAN-based Art Generator using Deep learning.ipynb
  Deep_Learning/GAN-based Art Generator using Deep learning/Model/README.md
  Deep_Learning/GAN-based Art Generator using Deep learning/requirements.txt
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#945 Anomaly Detection in Time Series
  Deep_Learning/Anomaly Detection in Time Series/Dataset/README.md
  Deep_Learning/Anomaly Detection in Time Series/Images/Image 1.png
  Deep_Learning/Anomaly Detection in Time Series/Images/Image 2.png
  Deep_Learning/Anomaly Detection in Time Series/Images/Image 3.png
  Deep_Learning/Anomaly Detection in Time Series/Images/Image 4.png
  Deep_Learning/Anomaly Detection in Time Series/Images/Image 5.png
  Deep_Learning/Anomaly Detection in Time Series/Model/Anomaly Detection in Time Series.ipynb
  Deep_Learning/Anomaly Detection in Time Series/Model/README.md
  Deep_Learning/Anomaly Detection in Time Series/requirements.txt
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#903 #883 Added the Memory Typing Game
  Game_Development/Memory Typing Game/README.md
  Game_Development/Memory Typing Game/main.py
  Project-Structure.md
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#683 Added algorithms for types of Gradient Descent
  Machine_Learning/Gradient_descent/README.md
  Machine_Learning/Gradient_descent/gradientdescent.ipynb
  Machine_Learning/Gradient_descent/homeprices_banglore.csv
Labels: Contributor, Status: Approved, level1, gssoc-ext, hacktoberfest

#900 Added the main code and readme file
  Image processing/Real-Time-Feature-Detection-and-Matching/Main.py
  Image processing/Real-Time-Feature-Detection-and-Matching/README.md
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#868 Fixes Issue #850 James_Web_Deep_Learning
  Deep_Learning/GAN-based Art Generator using Deep learning/Dataset/README.md
  Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image 1.png
  Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image 2.png
  Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image 3.png
  Deep_Learning/GAN-based Art Generator using Deep learning/Images/Image 4.png
  Deep_Learning/GAN-based Art Generator using Deep learning/Model/GAN-based Art Generator using Deep learning.ipynb
  Deep_Learning/GAN-based Art Generator using Deep learning/Model/README.md
  Deep_Learning/GAN-based Art Generator using Deep learning/requirements.txt
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest

#930 Fixes #928 Sentimental Analysis using Navie-Bayes-Classifier
  Deep_Learning/Sentimental_Analysis_navie/sentimental-analysis-using-naive-bayes-classifier.ipynb
  Project-Structure.md
Labels: Contributor, Status: Review Ongoing, level1, gssoc-ext, hacktoberfest
