Repository UTSAVS26/PyVerse, pull requests merged in 2025-09, with the labels that each got.

#1779 Addition of The DeepTRace-DeepFake detection using Chrome extension project
  Cybersecurity_Tools/DEEPFAKE/README.md
  Cybersecurity_Tools/DEEPFAKE/extension/backend/main.py
  Cybersecurity_Tools/DEEPFAKE/extension/backend/requirements.txt
  Cybersecurity_Tools/DEEPFAKE/extension/backend/test_image.jpg
  Cybersecurity_Tools/DEEPFAKE/extension/backend/test_image_request.py
  Cybersecurity_Tools/DEEPFAKE/extension/background.js
  Cybersecurity_Tools/DEEPFAKE/extension/content.js
  Cybersecurity_Tools/DEEPFAKE/extension/icons/icon128.png
  Cybersecurity_Tools/DEEPFAKE/extension/icons/icon16.png
  Cybersecurity_Tools/DEEPFAKE/extension/icons/icon48.png
  Cybersecurity_Tools/DEEPFAKE/extension/manifest.json
  Cybersecurity_Tools/DEEPFAKE/extension/popup.css
  Cybersecurity_Tools/DEEPFAKE/extension/popup.html
  Cybersecurity_Tools/DEEPFAKE/extension/popup.js
  Cybersecurity_Tools/DEEPFAKE/extension/style.css
  Cybersecurity_Tools/DEEPFAKE/package.json
Labels: Contributor, Status: Review Ongoing 🔄, level3, gssoc25

#1785 Added stack Problems(medium Leetcode) Rainwater trapping, asteroid co…
  Algorithms_and_Data_Structures/Stack/AsteroidCollision.py
  Algorithms_and_Data_Structures/Stack/NextGreaterElementii.py
  Algorithms_and_Data_Structures/Stack/TrappingRainWater.py
Labels: Contributor, Status: Review Ongoing 🔄, level2, gssoc25

#1780 Fixed Issue #1773: Added light/dark mode option to the Calculator App
  Beginner_Projects/Calculator_App/main.py
Labels: Contributor, Status: Review Ongoing 🔄, level1, gssoc25

#1795 Fixed issue #1789: Data Analysis doc update.
  Data_Science/Data_Analysis.md
Labels: Contributor, Status: Review Ongoing 🔄, level1, gssoc25
