Repository UTSAVS26/PyVerse, pull requests merged in 2025-07, with the labels that each got.

#1414 Academic Performance Regression Project
  Machine_Learning/Student-Performances-Based-On-Daily-Habits/Model.ipynb
  Machine_Learning/Student-Performances-Based-On-Daily-Habits/cleaneddf.csv
  Machine_Learning/Student-Performances-Based-On-Daily-Habits/readme.md
  Machine_Learning/Student-Performances-Based-On-Daily-Habits/student_habits_performance.csv
Labels: Contributor, Status: Approved ✔️, BEGINNER, SSOC S4

#1424 FIX #1404: Added a flask based using Gemini Api caption hashtag generator on basis of user mood
  Beginner_Projects/captionTags/.gitignore
  Beginner_Projects/captionTags/README.md
  Beginner_Projects/captionTags/Screenshots/home.png
  Beginner_Projects/captionTags/Screenshots/main.png
  Beginner_Projects/captionTags/app.py
  Beginner_Projects/captionTags/requirements.txt
  Beginner_Projects/captionTags/templates/index.html
Labels: Contributor, Status: Approved ✔️, INTERMEDIATE, SSOC S4

#1432 added resume upload and email sending feature
  Generative-AI/Cold-Email-Generator/app/.env
  Generative-AI/Cold-Email-Generator/app/app.py
  Generative-AI/Cold-Email-Generator/app/requirements.txt
Labels: Contributor, Status: Approved ✔️, INTERMEDIATE, SSOC S4

#1438 Add secure-shell
  Advanced_Projects/Secure-Shell-ws/README.md
  Advanced_Projects/Secure-Shell-ws/client/client.py
  Advanced_Projects/Secure-Shell-ws/client/utils.py
  Advanced_Projects/Secure-Shell-ws/config/config.json
  Advanced_Projects/Secure-Shell-ws/requirements.txt
  Advanced_Projects/Secure-Shell-ws/server/auth.py
  Advanced_Projects/Secure-Shell-ws/server/server.py
  Advanced_Projects/Secure-Shell-ws/server/shell_handler.py
  Advanced_Projects/Secure-Shell-ws/tests/test_auth.py
  Advanced_Projects/Secure-Shell-ws/tests/test_integration.py
  Advanced_Projects/Secure-Shell-ws/tests/test_shell_handler.py
  Advanced_Projects/Secure-Shell-ws/tests/test_utils.py
Labels: Contributor, Status: Approved ✔️, ADVANCE, SSOC S4

#1448 add Dynamic_Hardware_Resource_Monitor
  Advanced_Projects/hardware-monitor/README.md
  Advanced_Projects/hardware-monitor/__pycache__/test_project.cpython-313-pytest-8.4.1.pyc
  Advanced_Projects/hardware-monitor/gui/dashboard.py
  Advanced_Projects/hardware-monitor/main.py
  Advanced_Projects/hardware-monitor/models/__pycache__/lstm_predictor.cpython-313.pyc
  Advanced_Projects/hardware-monitor/models/__pycache__/stats_fallback.cpython-313.pyc
  Advanced_Projects/hardware-monitor/models/lstm_predictor.py
  Advanced_Projects/hardware-monitor/models/stats_fallback.py
  Advanced_Projects/hardware-monitor/requirements.txt
  Advanced_Projects/hardware-monitor/sensors/__pycache__/cpu.cpython-313.pyc
  Advanced_Projects/hardware-monitor/sensors/__pycache__/gpu.cpython-313.pyc
  Advanced_Projects/hardware-monitor/sensors/__pycache__/memory.cpython-313.pyc
  Advanced_Projects/hardware-monitor/sensors/cpu.py
  Advanced_Projects/hardware-monitor/sensors/gpu.py
  Advanced_Projects/hardware-monitor/sensors/memory.py
  Advanced_Projects/hardware-monitor/test_project.py
  Advanced_Projects/hardware-monitor/utils/__pycache__/config.cpython-313.pyc
  Advanced_Projects/hardware-monitor/utils/__pycache__/logger.cpython-313.pyc
  Advanced_Projects/hardware-monitor/utils/config.py
  Advanced_Projects/hardware-monitor/utils/logger.py
  Advanced_Projects/hardware-monitor/visualizations/__pycache__/live_plot.cpython-313.pyc
  Advanced_Projects/hardware-monitor/visualizations/__pycache__/prediction_overlay.cpython-313.pyc
  Advanced_Projects/hardware-monitor/visualizations/live_plot.py
  Advanced_Projects/hardware-monitor/visualizations/prediction_overlay.py
Labels: Contributor, Status: Approved ✔️, ADVANCE, SSOC S4

#1487 Enhancement: Added try-except blocks for input handling in anime trac…
  Beginner_Projects/Anime_Manga_Tracker/Anime_Manga_Tracker.py
Labels: Contributor, Status: Approved ✔️, level1, gssoc25

#1504 Add/ip changer for issue #1496
  Cybersecurity_Tools/IP-Changer/Config-Proxy.png
  Cybersecurity_Tools/IP-Changer/IP-ScreenShot.png
  Cybersecurity_Tools/IP-Changer/ip-changer.sh
  Cybersecurity_Tools/IP-Changer/readme.md
Labels: Contributor, Status: Approved ✔️, level1, gssoc25

#1500 Add BMI calculator with age and gender fields
  Beginner_Projects/BMI Calculator/BMI.py
Labels: Contributor, Status: Approved ✔️, level1, gssoc25

#1532 PyFlowViz: Code-to-Flowchart Auto Generator
  Advanced_Projects/PyFlowViz/README.md
  Advanced_Projects/PyFlowViz/examples/exception_handling.py
  Advanced_Projects/PyFlowViz/examples/loop_examples.py
  Advanced_Projects/PyFlowViz/examples/simple_function.py
  Advanced_Projects/PyFlowViz/exception_handling.html
  Advanced_Projects/PyFlowViz/gui/__init__.py
  Advanced_Projects/PyFlowViz/gui/app_gui.py
  Advanced_Projects/PyFlowViz/loop_examples.svg
  Advanced_Projects/PyFlowViz/parser/__init__.py
  Advanced_Projects/PyFlowViz/parser/ast_parser.py
  Advanced_Projects/PyFlowViz/parser/bytecode_parser.py
  Advanced_Projects/PyFlowViz/pyflowviz.py
  Advanced_Projects/PyFlowViz/requirements.txt
  Advanced_Projects/PyFlowViz/test_output.html
  Advanced_Projects/PyFlowViz/test_output.svg
  Advanced_Projects/PyFlowViz/test_output_bytecode.svg
  Advanced_Projects/PyFlowViz/test_output_fixed.svg
  Advanced_Projects/PyFlowViz/tests/__init__.py
  Advanced_Projects/PyFlowViz/tests/test_cli.py
  Advanced_Projects/PyFlowViz/tests/test_parser.py
  Advanced_Projects/PyFlowViz/tests/test_visualizer.py
  Advanced_Projects/PyFlowViz/visualizer/__init__.py
  Advanced_Projects/PyFlowViz/visualizer/graphviz_gen.py
  Advanced_Projects/PyFlowViz/visualizer/html_renderer.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1531 PySleuth: Context-Aware Python Debugger Implementation
  Advanced_Projects/PySleuth/README.md
  Advanced_Projects/PySleuth/core/__pycache__/ast_parser.cpython-313.pyc
  Advanced_Projects/PySleuth/core/__pycache__/explainer.cpython-313.pyc
  Advanced_Projects/PySleuth/core/__pycache__/logger.cpython-313.pyc
  Advanced_Projects/PySleuth/core/__pycache__/tracer.cpython-313.pyc
  Advanced_Projects/PySleuth/core/ast_parser.py
  Advanced_Projects/PySleuth/core/explainer.py
  Advanced_Projects/PySleuth/core/logger.py
  Advanced_Projects/PySleuth/core/tracer.py
  Advanced_Projects/PySleuth/decorators/__pycache__/trace.cpython-313.pyc
  Advanced_Projects/PySleuth/decorators/trace.py
  Advanced_Projects/PySleuth/examples/sample_scripts.py
  Advanced_Projects/PySleuth/pysleuth.py
  Advanced_Projects/PySleuth/requirements.txt
  Advanced_Projects/PySleuth/test_trace_decorator_log.json
  Advanced_Projects/PySleuth/tests/__pycache__/test_ast_parser.cpython-313.pyc
  Advanced_Projects/PySleuth/tests/__pycache__/test_explainer.cpython-313.pyc
  Advanced_Projects/PySleuth/tests/__pycache__/test_logger.cpython-313.pyc
  Advanced_Projects/PySleuth/tests/__pycache__/test_tracer_and_decorator.cpython-313.pyc
  Advanced_Projects/PySleuth/tests/test_ast_parser.py
  Advanced_Projects/PySleuth/tests/test_explainer.py
  Advanced_Projects/PySleuth/tests/test_logger.py
  Advanced_Projects/PySleuth/tests/test_tracer_and_decorator.py
  Advanced_Projects/PySleuth/tui/curses_ui.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1529 Smart GUI-based PDF-to-Text Extractor with Advanced OCR and AI Correction
  Advanced_Projects/PDFTextGenie/README.md
  Advanced_Projects/PDFTextGenie/app.py
  Advanced_Projects/PDFTextGenie/gui/__init__.py
  Advanced_Projects/PDFTextGenie/gui/main_window.py
  Advanced_Projects/PDFTextGenie/ocr/__init__.py
  Advanced_Projects/PDFTextGenie/ocr/llama_ocr.py
  Advanced_Projects/PDFTextGenie/ocr/postprocess.py
  Advanced_Projects/PDFTextGenie/requirements.txt
  Advanced_Projects/PDFTextGenie/tests/test_pdftextgenie.py
  Advanced_Projects/PDFTextGenie/utils/__init__.py
  Advanced_Projects/PDFTextGenie/utils/pdf_utils.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1527 SmartCLI: Natural Language Command-Line Toolkit Implementation
  Advanced_Projects/SmartCLI/README.md
  Advanced_Projects/SmartCLI/core/command_map.py
  Advanced_Projects/SmartCLI/core/executor.py
  Advanced_Projects/SmartCLI/core/parser.py
  Advanced_Projects/SmartCLI/core/utils.py
  Advanced_Projects/SmartCLI/models/.gitkeep
  Advanced_Projects/SmartCLI/requirements.txt
  Advanced_Projects/SmartCLI/smartcli.py
  Advanced_Projects/SmartCLI/test_smartcli.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1484 Addition of Optimization_Algorithms/Evolutionary_Algorithms/Genetic_Algorithms
  Optimization_Algorithms/.gitkeep
  Optimization_Algorithms/Genetic_Algorithms/README.md
  Optimization_Algorithms/Genetic_Algorithms/knapsack_problem.py
Labels: Contributor, Status: Requested Changes⚙️, level3, gssoc25
