Repository UTSAVS26/PyVerse, pull requests merged in 2025-08, with the labels that each got.

#1547 PyRecon: High-Speed Port Scanner & Service Fingerprinter - Complete Implementation
  Cybersecurity_Tools/PyRecon/PROJECT_SUMMARY.md
  Cybersecurity_Tools/PyRecon/README.md
  Cybersecurity_Tools/PyRecon/demo.py
  Cybersecurity_Tools/PyRecon/examples/targets.txt
  Cybersecurity_Tools/PyRecon/pyproject.toml
  Cybersecurity_Tools/PyRecon/pyrecon/__init__.py
  Cybersecurity_Tools/PyRecon/pyrecon/cli/__init__.py
  Cybersecurity_Tools/PyRecon/pyrecon/cli/main.py
  Cybersecurity_Tools/PyRecon/pyrecon/core/__init__.py
  Cybersecurity_Tools/PyRecon/pyrecon/core/banner_grabber.py
  Cybersecurity_Tools/PyRecon/pyrecon/core/os_fingerprint.py
  Cybersecurity_Tools/PyRecon/pyrecon/core/scanner.py
  Cybersecurity_Tools/PyRecon/pyrecon/core/utils.py
  Cybersecurity_Tools/PyRecon/pyrecon/output/__init__.py
  Cybersecurity_Tools/PyRecon/pyrecon/output/formatter.py
  Cybersecurity_Tools/PyRecon/pyrecon/plugins/__init__.py
  Cybersecurity_Tools/PyRecon/pyrecon/plugins/http_fingerprint.py
  Cybersecurity_Tools/PyRecon/pyrecon/plugins/tls_parser.py
  Cybersecurity_Tools/PyRecon/requirements.txt
  Cybersecurity_Tools/PyRecon/setup.py
  Cybersecurity_Tools/PyRecon/test_installation.py
  Cybersecurity_Tools/PyRecon/tests/__init__.py
  Cybersecurity_Tools/PyRecon/tests/test_scanner.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1549 ClipCrypt: Encrypted Clipboard Manager - Secure, searchable, and local-only clipboard history
  Cybersecurity_Tools/ClipCrypt/README.md
  Cybersecurity_Tools/ClipCrypt/clipcrypt/__init__.py
  Cybersecurity_Tools/ClipCrypt/clipcrypt/__main__.py
  Cybersecurity_Tools/ClipCrypt/clipcrypt/cli.py
  Cybersecurity_Tools/ClipCrypt/clipcrypt/clipboard.py
  Cybersecurity_Tools/ClipCrypt/clipcrypt/core.py
  Cybersecurity_Tools/ClipCrypt/clipcrypt/encryption.py
  Cybersecurity_Tools/ClipCrypt/clipcrypt/storage.py
  Cybersecurity_Tools/ClipCrypt/demo.py
  Cybersecurity_Tools/ClipCrypt/requirements.txt
  Cybersecurity_Tools/ClipCrypt/setup.py
  Cybersecurity_Tools/ClipCrypt/tests/__init__.py
  Cybersecurity_Tools/ClipCrypt/tests/test_clipboard.py
  Cybersecurity_Tools/ClipCrypt/tests/test_core.py
  Cybersecurity_Tools/ClipCrypt/tests/test_encryption.py
  Cybersecurity_Tools/ClipCrypt/tests/test_storage.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1551 PyTerminus: Virtual Multi-Terminal Manager in Python - Complete Implementation
  Advanced_Projects/PyTerminus/.coverage
  Advanced_Projects/PyTerminus/PROJECT_SUMMARY.md
  Advanced_Projects/PyTerminus/README.md
  Advanced_Projects/PyTerminus/core/__init__.py
  Advanced_Projects/PyTerminus/core/logger.py
  Advanced_Projects/PyTerminus/core/session_manager.py
  Advanced_Projects/PyTerminus/core/terminal_pane.py
  Advanced_Projects/PyTerminus/demo.py
  Advanced_Projects/PyTerminus/demo_logs/commands.log
  Advanced_Projects/PyTerminus/demo_logs/output.log
  Advanced_Projects/PyTerminus/demo_logs/session.log
  Advanced_Projects/PyTerminus/profiles/sample_session.yaml
  Advanced_Projects/PyTerminus/profiles/web_dev.yaml
  Advanced_Projects/PyTerminus/pyterminus.py
  Advanced_Projects/PyTerminus/requirements.txt
  Advanced_Projects/PyTerminus/tests/__init__.py
  Advanced_Projects/PyTerminus/tests/conftest.py
  Advanced_Projects/PyTerminus/tests/test_keybindings.py
  Advanced_Projects/PyTerminus/tests/test_layout.py
  Advanced_Projects/PyTerminus/tests/test_logger.py
  Advanced_Projects/PyTerminus/tests/test_logger_simple.py
  Advanced_Projects/PyTerminus/tests/test_session_manager.py
  Advanced_Projects/PyTerminus/tui/__init__.py
  Advanced_Projects/PyTerminus/tui/keybindings.py
  Advanced_Projects/PyTerminus/tui/layout.py
  Advanced_Projects/PyTerminus/tui/main_ui.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1523 Added Reverse_backdoor ( backdoor.py and listener.py )
  Cybersecurity_Tools/Reverse_backdoor/Listener.py
  Cybersecurity_Tools/Reverse_backdoor/backdoor.py
Labels: Contributor, Status: Review Ongoing 🔄, level2, gssoc25

#1525 Add Customer Churn Prediction ML Project – Resolved #1520
  Machine_Learning/Customer_Churn_Prediction/CustomerChurnPrediction.ipynb
  Machine_Learning/Customer_Churn_Prediction/README.md
  Machine_Learning/Customer_Churn_Prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
  Machine_Learning/Customer_Churn_Prediction/requirements.txt
Labels: Contributor, Status: Review Ongoing 🔄, level1, gssoc25

#1540 Refactor/generic linked list
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Circular_Doubly_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Circular_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Doubly_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Dynamic_Linear_Queue_using_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Dynamic_Stack_using_LinkedList.py
  Algorithms_and_Data_Structures/Linked List/Menu_Driven_Code_for_Linear_LinkedList.py
Labels: Contributor, Status: Approved ✔️, level3, gssoc25

#1558 Heart Disease Prediction (Logistic Regression, Decision Tree, Random Forest)
  Machine_Learning/Heart Disease Prediction/Heart Disease Prediction (LogisticRegression, DecisionTree, RandomForest).ipynb
  Machine_Learning/Heart Disease Prediction/README.md
  Machine_Learning/Heart Disease Prediction/heart_cleveland_upload.csv
Labels: Contributor, Status: Approved ✔️, Beginner, SSoC25

#1559 Bug fix of ATM.py
  Beginner_Projects/ATM Interface/ATM.py
Labels: Contributor, Status: Review Ongoing 🔄, level1, gssoc25

#1563 Behavior-Based Script Detector: Static Analysis Tool for Python Security
  Cybersecurity_Tools/Behavior-Based Script Detector/PROJECT_SUMMARY.md
  Cybersecurity_Tools/Behavior-Based Script Detector/README.md
  Cybersecurity_Tools/Behavior-Based Script Detector/analyzer/__init__.py
  Cybersecurity_Tools/Behavior-Based Script Detector/analyzer/pattern_rules.py
  Cybersecurity_Tools/Behavior-Based Script Detector/analyzer/report_generator.py
  Cybersecurity_Tools/Behavior-Based Script Detector/analyzer/score_calculator.py
  Cybersecurity_Tools/Behavior-Based Script Detector/cli/__init__.py
  Cybersecurity_Tools/Behavior-Based Script Detector/cli/main.py
  Cybersecurity_Tools/Behavior-Based Script Detector/demo.py
  Cybersecurity_Tools/Behavior-Based Script Detector/examples/test_malicious.py
  Cybersecurity_Tools/Behavior-Based Script Detector/examples/test_safe.py
  Cybersecurity_Tools/Behavior-Based Script Detector/requirements.txt
  Cybersecurity_Tools/Behavior-Based Script Detector/run_tests.py
  Cybersecurity_Tools/Behavior-Based Script Detector/tests/__init__.py
  Cybersecurity_Tools/Behavior-Based Script Detector/tests/test_patterns.py
  Cybersecurity_Tools/Behavior-Based Script Detector/utils/__init__.py
  Cybersecurity_Tools/Behavior-Based Script Detector/utils/file_loader.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1567 PDF Intelligence Extractor - Intelligent Document Parser for PDFs
  Cybersecurity_Tools/PDF Intelligence Extractor/README.md
  Cybersecurity_Tools/PDF Intelligence Extractor/demo.py
  Cybersecurity_Tools/PDF Intelligence Extractor/demo_invoice_output.json
  Cybersecurity_Tools/PDF Intelligence Extractor/demo_research_output.json
  Cybersecurity_Tools/PDF Intelligence Extractor/demo_resume_output.json
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/__init__.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/cli/__init__.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/cli/main.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/extractors/__init__.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/extractors/base_parser.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/extractors/invoice_parser.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/extractors/research_parser.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/extractors/resume_parser.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/tests/__init__.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/tests/test_invoice_parser.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/tests/test_research_parser.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/tests/test_resume_parser.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/utils/__init__.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/utils/ai_helpers.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/utils/file_utils.py
  Cybersecurity_Tools/PDF Intelligence Extractor/pdf_intelligence_extractor/utils/table_utils.py
  Cybersecurity_Tools/PDF Intelligence Extractor/requirements.txt
  Cybersecurity_Tools/PDF Intelligence Extractor/requirements_simple.txt
  Cybersecurity_Tools/PDF Intelligence Extractor/run_tests.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1576 Random Story Generator
  Beginner_Projects/Random_Story_Generator/main.py
Labels: Contributor, Status: Review Ongoing 🔄, level2, gssoc25

#1519 <NEW PROJECT PULL REQUEST > SCREEN TIME TRACKER
  Beginner_Projects/ScreenTimeTracker/README.txt
  Beginner_Projects/ScreenTimeTracker/analyzer.py
  Beginner_Projects/ScreenTimeTracker/assets/heatmap_20250731_221353.png
  Beginner_Projects/ScreenTimeTracker/assets/pie_chart.png
  Beginner_Projects/ScreenTimeTracker/heatmap_generator.py
  Beginner_Projects/ScreenTimeTracker/logs/log.csv
  Beginner_Projects/ScreenTimeTracker/logs/screen_log.csv
  Beginner_Projects/ScreenTimeTracker/main.py
  Beginner_Projects/ScreenTimeTracker/tracker.py
  Beginner_Projects/ScreenTimeTracker/ui.py
  assets/chart_20250728_195352.png
  assets/chart_20250728_195413.png
  assets/heatmap_20250728_210423.png
  assets/heatmap_20250728_211159.png
  assets/heatmap_20250728_220405.png
  assets/pie_chart.png
  assets/screentime_20250728_194809.png
  assets/screentime_20250728_195019.png
  assets/screentime_20250728_195024.png
  assets/screentime_20250728_195040.png
  assets/screentime_20250728_204937.png
  logs/log.csv
  logs/screen_log.csv
Labels: Contributor, Status: Review Ongoing 🔄, level1, gssoc25

#1550 LightFlow: A Lightweight Parallel Task Pipeline Framework
  Web_Development/LightFlow/.coverage
  Web_Development/LightFlow/README.md
  Web_Development/LightFlow/examples/basic_workflow.yaml
  Web_Development/LightFlow/examples/parallel_workflow.yaml
  Web_Development/LightFlow/examples/python_workflow.yaml
  Web_Development/LightFlow/lightflow/__init__.py
  Web_Development/LightFlow/lightflow/cli/__init__.py
  Web_Development/LightFlow/lightflow/cli/main.py
  Web_Development/LightFlow/lightflow/engine/__init__.py
  Web_Development/LightFlow/lightflow/engine/checkpoint.py
  Web_Development/LightFlow/lightflow/engine/dag_builder.py
  Web_Development/LightFlow/lightflow/engine/executor.py
  Web_Development/LightFlow/lightflow/engine/logger.py
  Web_Development/LightFlow/lightflow/parser/__init__.py
  Web_Development/LightFlow/lightflow/parser/workflow_loader.py
  Web_Development/LightFlow/lightflow/plugins/__init__.py
  Web_Development/LightFlow/lightflow/plugins/python_task.py
  Web_Development/LightFlow/lightflow/plugins/shell_task.py
  Web_Development/LightFlow/lightflow/visuals/__init__.py
  Web_Development/LightFlow/lightflow/visuals/dag_viewer.py
  Web_Development/LightFlow/my_test_workflow_template.yaml
  Web_Development/LightFlow/requirements.txt
  Web_Development/LightFlow/setup.py
  Web_Development/LightFlow/tests/__init__.py
  Web_Development/LightFlow/tests/test_checkpoint.py
  Web_Development/LightFlow/tests/test_dag_builder.py
  Web_Development/LightFlow/tests/test_executor.py
  Web_Development/LightFlow/tests/test_workflow_loader.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1463 Added several new features in BST code such as finding min/max key, cloning tree, mirroring tree and pretty print of tree
  Algorithms_and_Data_Structures/BinarySearchTree/__pycache__/bst.cpython-312.pyc
  Algorithms_and_Data_Structures/BinarySearchTree/__pycache__/bstnode.cpython-312.pyc
  Algorithms_and_Data_Structures/BinarySearchTree/bst.py
  Algorithms_and_Data_Structures/BinarySearchTree/main.py
Labels: Contributor, Status: Review Ongoing 🔄, level2, gssoc25

#1566 Chroot
  Cybersecurity_Tools/Chroot Lite/PROJECT_SUMMARY.md
  Cybersecurity_Tools/Chroot Lite/README.md
  Cybersecurity_Tools/Chroot Lite/cli/__init__.py
  Cybersecurity_Tools/Chroot Lite/cli/main.py
  Cybersecurity_Tools/Chroot Lite/examples/test_script.py
  Cybersecurity_Tools/Chroot Lite/requirements.txt
  Cybersecurity_Tools/Chroot Lite/sandbox/__init__.py
  Cybersecurity_Tools/Chroot Lite/sandbox/executor.py
  Cybersecurity_Tools/Chroot Lite/sandbox/firewall.py
  Cybersecurity_Tools/Chroot Lite/sandbox/limiter.py
  Cybersecurity_Tools/Chroot Lite/sandbox/manager.py
  Cybersecurity_Tools/Chroot Lite/test_cli.py
  Cybersecurity_Tools/Chroot Lite/tests/__init__.py
  Cybersecurity_Tools/Chroot Lite/tests/test_executor.py
  Cybersecurity_Tools/Chroot Lite/tests/test_integration.py
  Cybersecurity_Tools/Chroot Lite/tests/test_limiter.py
  Cybersecurity_Tools/Chroot Lite/tests/test_manager.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1582 Enhnacement ML/#1555
  Machine_Learning/Heart Disease Prediction [END 2 END]/Heart Disease Prediction.ipynb
Labels: Contributor, Status: Review Ongoing 🔄, level1, gssoc25

#1596 Resolved Issue #1591: Added Medium-level Array questions.
  Algorithms_and_Data_Structures/Arrays/3Sum.py
  Algorithms_and_Data_Structures/Arrays/Single_number.py
  Algorithms_and_Data_Structures/Arrays/find_duplicate.py
  Algorithms_and_Data_Structures/Arrays/peak_element.py
  Algorithms_and_Data_Structures/Arrays/removeDuplicates.py
  Algorithms_and_Data_Structures/Arrays/search2D.py
Labels: Contributor, Status: Approved ✔️, level1, gssoc25

#1597 Added youtube_RAG_ChatBot-GenerativeAI
  Generative-AI/Youtube_Rag_Chatbot/.env.example
  Generative-AI/Youtube_Rag_Chatbot/README.md
  Generative-AI/Youtube_Rag_Chatbot/app.py
  Generative-AI/Youtube_Rag_Chatbot/main.py
  Generative-AI/Youtube_Rag_Chatbot/requirements.txt
  Generative-AI/Youtube_Rag_Chatbot/screenshots/Screenshot.png
Labels: Contributor, Status: Review Ongoing 🔄, level3, gssoc25

#1627 Added Advanced Multi-Agent Debate DAG Project using LangGraph (Debate AI) to 'Advanced_Projects'
  Advanced_Projects/MultiAgent_Debate_DAG/.env.example
  Advanced_Projects/MultiAgent_Debate_DAG/.gitignore
  Advanced_Projects/MultiAgent_Debate_DAG/README.md
  Advanced_Projects/MultiAgent_Debate_DAG/dag_diagram.png
  Advanced_Projects/MultiAgent_Debate_DAG/dag_diagram.py
  Advanced_Projects/MultiAgent_Debate_DAG/debate_chat_log.txt
  Advanced_Projects/MultiAgent_Debate_DAG/main.py
  Advanced_Projects/MultiAgent_Debate_DAG/nodes/agent_a.py
  Advanced_Projects/MultiAgent_Debate_DAG/nodes/agent_b.py
  Advanced_Projects/MultiAgent_Debate_DAG/nodes/judge_node.py
  Advanced_Projects/MultiAgent_Debate_DAG/nodes/memory_node.py
  Advanced_Projects/MultiAgent_Debate_DAG/nodes/user_input.py
  Advanced_Projects/MultiAgent_Debate_DAG/requirements.txt
Labels: Contributor, Status: Review Ongoing 🔄, level3, gssoc25

#1630 PassClass: AI-Powered Password Strength Classifier
  Deep_Learning/PassClass/README.md
  Deep_Learning/PassClass/data/generate_passwords.py
  Deep_Learning/PassClass/data/password_dataset.csv
  Deep_Learning/PassClass/labeling/labeler.py
  Deep_Learning/PassClass/models/logistic_regression_password_classifier.pkl
  Deep_Learning/PassClass/models/random_forest_password_classifier.pkl
  Deep_Learning/PassClass/models/svm_password_classifier.pkl
  Deep_Learning/PassClass/models/tfidf_classifier.py
  Deep_Learning/PassClass/requirements.txt
  Deep_Learning/PassClass/tests/test_generation.py
  Deep_Learning/PassClass/training/evaluate.py
  Deep_Learning/PassClass/training/evaluation/confidence_distribution.png
  Deep_Learning/PassClass/training/evaluation/confusion_matrix.png
  Deep_Learning/PassClass/training/evaluation/per_class_metrics.png
  Deep_Learning/PassClass/training/evaluation/roc_auc_scores.png
  Deep_Learning/PassClass/training/evaluation_report.txt
  Deep_Learning/PassClass/training/model_comparison.png
  Deep_Learning/PassClass/training/random_forest_confusion_matrix.png
  Deep_Learning/PassClass/training/train_model.py
  Deep_Learning/PassClass/ui/streamlit_app.py
  Deep_Learning/PassClass/utils/metrics.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1631 MoodMeet: AI-Powered Meeting Mood Analyzer
  Deep_Learning/MoodMeet/PROJECT_SUMMARY.md
  Deep_Learning/MoodMeet/README.md
  Deep_Learning/MoodMeet/analysis/keyword_extractor.py
  Deep_Learning/MoodMeet/analysis/mood_clustering.py
  Deep_Learning/MoodMeet/analysis/sentiment_analyzer.py
  Deep_Learning/MoodMeet/data/example_transcripts/sample_meeting.txt
  Deep_Learning/MoodMeet/data/uploader.py
  Deep_Learning/MoodMeet/demo.py
  Deep_Learning/MoodMeet/models/transformer_sentiment.py
  Deep_Learning/MoodMeet/requirements.txt
  Deep_Learning/MoodMeet/tests/test_sentiment.py
  Deep_Learning/MoodMeet/ui/streamlit_app.py
  Deep_Learning/MoodMeet/visualization/heatmap_generator.py
  Deep_Learning/MoodMeet/visualization/mood_timeline.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1637 TextPersona: Personality Type Predictor from Reflective Prompts
  Deep_Learning/TextPersona/PR_DESCRIPTION.md
  Deep_Learning/TextPersona/README.md
  Deep_Learning/TextPersona/core/classifier_rules.py
  Deep_Learning/TextPersona/core/classifier_zero_shot.py
  Deep_Learning/TextPersona/core/prompt_interface.py
  Deep_Learning/TextPersona/core/result_formatter.py
  Deep_Learning/TextPersona/data/.gitkeep
  Deep_Learning/TextPersona/data/user_logs.json
  Deep_Learning/TextPersona/demo.py
  Deep_Learning/TextPersona/demo_results.txt
  Deep_Learning/TextPersona/main.py
  Deep_Learning/TextPersona/prompts/mbti_descriptions.md
  Deep_Learning/TextPersona/prompts/questions.json
  Deep_Learning/TextPersona/requirements.txt
  Deep_Learning/TextPersona/tests/test_classifier.py
  Deep_Learning/TextPersona/ui/streamlit_app.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1638 TicTacRL: Self-Play Tic-Tac-Toe Agent using Reinforcement Learning
  Deep_Learning/TicTacRL/PR_DESCRIPTION.md
  Deep_Learning/TicTacRL/README.md
  Deep_Learning/TicTacRL/__init__.py
  Deep_Learning/TicTacRL/agents/__init__.py
  Deep_Learning/TicTacRL/agents/base_agent.py
  Deep_Learning/TicTacRL/agents/monte_carlo_agent.py
  Deep_Learning/TicTacRL/agents/q_learning_agent.py
  Deep_Learning/TicTacRL/env/__init__.py
  Deep_Learning/TicTacRL/env/tictactoe_env.py
  Deep_Learning/TicTacRL/evaluation/__init__.py
  Deep_Learning/TicTacRL/evaluation/evaluate_vs_random.py
  Deep_Learning/TicTacRL/monte_carlo_training.png
  Deep_Learning/TicTacRL/q_learning_training.png
  Deep_Learning/TicTacRL/requirements.txt
  Deep_Learning/TicTacRL/tests/__init__.py
  Deep_Learning/TicTacRL/tests/test_env.py
  Deep_Learning/TicTacRL/trained_mc_agent.pkl
  Deep_Learning/TicTacRL/trained_q_agent.pkl
  Deep_Learning/TicTacRL/training/__init__.py
  Deep_Learning/TicTacRL/training/self_play_mc.py
  Deep_Learning/TicTacRL/training/self_play_qlearn.py
  Deep_Learning/TicTacRL/ui/__init__.py
  Deep_Learning/TicTacRL/ui/play_against_ai.py
  Deep_Learning/TicTacRL/utils/__init__.py
  Deep_Learning/TicTacRL/utils/state_utils.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1626 Add Speech Emotion Recognition Feature to PyVerse
  Deep_Learning/Speech_Emotion_Recognition/.gitattributes
  Deep_Learning/Speech_Emotion_Recognition/Emotion_Voice_Detection_Model.pkl
  Deep_Learning/Speech_Emotion_Recognition/README.md
  Deep_Learning/Speech_Emotion_Recognition/app.py
  Deep_Learning/Speech_Emotion_Recognition/model.pkl
  Deep_Learning/Speech_Emotion_Recognition/predictionfinal.csv
  Deep_Learning/Speech_Emotion_Recognition/requirements.txt
Labels: Contributor, Status: Review Ongoing 🔄, level2, gssoc25

#1647 Proposal: Add "Crypto Report Generator and Dashboard" to Data Science Folder
  Data_Science/crypto_report_dashboard/README.md
  Data_Science/crypto_report_dashboard/crypto_report.py
  Data_Science/crypto_report_dashboard/requirements.txt
Labels: Contributor, Status: Review Ongoing 🔄, level2, gssoc25

#1662 Added a Titanic Survival Prediction Project
  Machine_Learning/titanic-survival-prediction/data/test.csv
  Machine_Learning/titanic-survival-prediction/data/train.csv
  Machine_Learning/titanic-survival-prediction/notebooks/titanic_xgboost.ipynb
  Machine_Learning/titanic-survival-prediction/requirements.txt
Labels: Contributor, Status: Approved ✔️, level1, gssoc25

#1665 Sentiment analysis of Whatsapp chat
  Machine_Learning/Sentiment analysis for Whatsapp/Dataset/WhatsApp (1).csv
  Machine_Learning/Sentiment analysis for Whatsapp/Model/Whatsapp_chat_app_ananlysis.ipynb
Labels: Contributor, Status: Approved ✔️, level2, gssoc25

#1690 AI Flashcard Generator from PDFs with NLP-Powered Question Generation
  Deep_Learning/VoiceMoodMirror/README.md
  Deep_Learning/VoiceMoodMirror/debug_answer_selector.py
  Deep_Learning/VoiceMoodMirror/debug_footnote.py
  Deep_Learning/VoiceMoodMirror/examples/sample_text.txt
  Deep_Learning/VoiceMoodMirror/flashgenie/__init__.py
  Deep_Learning/VoiceMoodMirror/flashgenie/flashcard/__init__.py
  Deep_Learning/VoiceMoodMirror/flashgenie/flashcard/export.py
  Deep_Learning/VoiceMoodMirror/flashgenie/flashcard/flashcard_formatter.py
  Deep_Learning/VoiceMoodMirror/flashgenie/main.py
  Deep_Learning/VoiceMoodMirror/flashgenie/nlp/__init__.py
  Deep_Learning/VoiceMoodMirror/flashgenie/nlp/answer_selector.py
  Deep_Learning/VoiceMoodMirror/flashgenie/nlp/keyword_extractor.py
  Deep_Learning/VoiceMoodMirror/flashgenie/nlp/question_generator.py
  Deep_Learning/VoiceMoodMirror/flashgenie/pdf_parser/__init__.py
  Deep_Learning/VoiceMoodMirror/flashgenie/pdf_parser/extract_text.py
  Deep_Learning/VoiceMoodMirror/flashgenie/preprocessing/__init__.py
  Deep_Learning/VoiceMoodMirror/flashgenie/preprocessing/chunker.py
  Deep_Learning/VoiceMoodMirror/flashgenie/preprocessing/clean_text.py
  Deep_Learning/VoiceMoodMirror/requirements.txt
  Deep_Learning/VoiceMoodMirror/test_simple.py
  Deep_Learning/VoiceMoodMirror/tests/__init__.py
  Deep_Learning/VoiceMoodMirror/tests/test_flashcard.py
  Deep_Learning/VoiceMoodMirror/tests/test_nlp.py
  Deep_Learning/VoiceMoodMirror/tests/test_pdf_parser.py
  Deep_Learning/VoiceMoodMirror/tests/test_preprocessing.py
  Deep_Learning/VoiceMoodMirror/ui/__init__.py
  Deep_Learning/VoiceMoodMirror/ui/app.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1689 Logic Puzzle Solver with Natural Language Processing and Symbolic Reasoning
  Deep_Learning/RiddleMind/.coverage
  Deep_Learning/RiddleMind/README.md
  Deep_Learning/RiddleMind/example.py
  Deep_Learning/RiddleMind/requirements.txt
  Deep_Learning/RiddleMind/riddlemind/__init__.py
  Deep_Learning/RiddleMind/riddlemind/cli.py
  Deep_Learning/RiddleMind/riddlemind/constraints.py
  Deep_Learning/RiddleMind/riddlemind/parser.py
  Deep_Learning/RiddleMind/riddlemind/solver.py
  Deep_Learning/RiddleMind/riddlemind/web_app.py
  Deep_Learning/RiddleMind/setup.py
  Deep_Learning/RiddleMind/tests/__init__.py
  Deep_Learning/RiddleMind/tests/test_constraints.py
  Deep_Learning/RiddleMind/tests/test_parser.py
  Deep_Learning/RiddleMind/tests/test_solver.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1687 AI-Powered Habit Tracking with Pattern Detection and Predictive Insights
  Deep_Learning/AIHabitTracker/.coverage
  Deep_Learning/AIHabitTracker/DEMO.md
  Deep_Learning/AIHabitTracker/README.md
  Deep_Learning/AIHabitTracker/USAGE.md
  Deep_Learning/AIHabitTracker/data/habits.db
  Deep_Learning/AIHabitTracker/requirements.txt
  Deep_Learning/AIHabitTracker/run_cli.py
  Deep_Learning/AIHabitTracker/run_gui.py
  Deep_Learning/AIHabitTracker/src/__init__.py
  Deep_Learning/AIHabitTracker/src/analysis/__init__.py
  Deep_Learning/AIHabitTracker/src/analysis/pattern_detector.py
  Deep_Learning/AIHabitTracker/src/analysis/visualizer.py
  Deep_Learning/AIHabitTracker/src/cli_app.py
  Deep_Learning/AIHabitTracker/src/gui_app.py
  Deep_Learning/AIHabitTracker/src/models/__init__.py
  Deep_Learning/AIHabitTracker/src/models/database.py
  Deep_Learning/AIHabitTracker/src/models/habit_model.py
  Deep_Learning/AIHabitTracker/src/streamlit_app.py
  Deep_Learning/AIHabitTracker/tests/__init__.py
  Deep_Learning/AIHabitTracker/tests/test_analysis.py
  Deep_Learning/AIHabitTracker/tests/test_integration.py
  Deep_Learning/AIHabitTracker/tests/test_models.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1684 Automated Machine Learning Engine with Universal CSV Support and Interactive UI
  Deep_Learning/QuickML/PROJECT_SUMMARY.md
  Deep_Learning/QuickML/README.md
  Deep_Learning/QuickML/app.py
  Deep_Learning/QuickML/best_model.pkl
  Deep_Learning/QuickML/demo.py
  Deep_Learning/QuickML/demo_classification_model.pkl
  Deep_Learning/QuickML/demo_regression_model.pkl
  Deep_Learning/QuickML/plots/confusion_matrix.png
  Deep_Learning/QuickML/plots/data_distribution.png
  Deep_Learning/QuickML/plots/feature_importance.png
  Deep_Learning/QuickML/plots/model_comparison.png
  Deep_Learning/QuickML/plots/prediction_vs_actual.png
  Deep_Learning/QuickML/plots/roc_curve.png
  Deep_Learning/QuickML/quickml.py
  Deep_Learning/QuickML/quickml/__init__.py
  Deep_Learning/QuickML/quickml/core.py
  Deep_Learning/QuickML/quickml/evaluation.py
  Deep_Learning/QuickML/quickml/models.py
  Deep_Learning/QuickML/quickml/preprocessing.py
  Deep_Learning/QuickML/quickml/visualization.py
  Deep_Learning/QuickML/requirements.txt
  Deep_Learning/QuickML/sample_data.py
  Deep_Learning/QuickML/sample_data/classification_data.csv
  Deep_Learning/QuickML/sample_data/customer_churn.csv
  Deep_Learning/QuickML/sample_data/house_prices.csv
  Deep_Learning/QuickML/sample_data/regression_data.csv
  Deep_Learning/QuickML/tests/__init__.py
  Deep_Learning/QuickML/tests/test_quickml.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1682 Implementation of Chinese Remainder Theorem Algorithm
  Algorithms_and_Data_Structures/Advanced Algorithms/chinese_remainder_theorem/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/chinese_remainder_theorem/chinese_remainder_theorem.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1680 Implementation of Beam Search Algorithm
  Algorithms_and_Data_Structures/Advanced Algorithms/Beam_Search/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Beam_Search/beam_search.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1678 Implementation of Fibonacci Heap Data Structure
  Algorithms_and_Data_Structures/Advanced Algorithms/Fibonacci_Heap/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Fibonacci_Heap/fibonacci_heap.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1676 Implementation of Euler Tour Technique
  Algorithms_and_Data_Structures/Advanced Algorithms/Euler_Tour_Technique/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Euler_Tour_Technique/euler_tour_technique.py
  Algorithms_and_Data_Structures/Advanced Algorithms/Euler_Tour_Technique/euler_tour_visualization.png
  Algorithms_and_Data_Structures/Advanced Algorithms/Euler_Tour_Technique/subtree_query_1.png
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1724 Implementation of Minimum Spanning Tree Algorithms (Kruskal's and Prim's) with Visualization
  Algorithms_and_Data_Structures/Advanced Algorithms/Minimum_Spanning_Tree/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Minimum_Spanning_Tree/minimum_spanning_tree.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1725 Implementation of Manacher's Algorithm for Longest Palindromic Substring with Advanced Features
  Algorithms_and_Data_Structures/Advanced Algorithms/Manachers_Algorithm/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Manachers_Algorithm/manachers_algorithm.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1726 Implementation of Link-Cut Tree Data Structure for Dynamic Connectivity and Path Queries
  Algorithms_and_Data_Structures/Advanced Algorithms/Link_Cut_Tree/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Link_Cut_Tree/link_cut_tree.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1728 Implementation of Monte Carlo Tree Search (MCTS) Algorithm with Multiple Game Examples
  Algorithms_and_Data_Structures/Advanced Algorithms/Monte_Carlo_Tree_Search/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Monte_Carlo_Tree_Search/mcts.py
Labels: Contributor, Status: Approved ✔️, Advanced, SSoC25

#1742 Implementation of Skip List Data Structure with Advanced Features and Visualization
  Algorithms_and_Data_Structures/Advanced Algorithms/Skip_List/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Skip_List/skip_list.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1741 Implementation of Simulated Annealing Algorithm with Multiple Optimization Problem Examples
  Algorithms_and_Data_Structures/Advanced Algorithms/Simulated_Annealing/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Simulated_Annealing/simulated_annealing.py
Labels: Contributor, Status: Review Ongoing 🔄, Intermediate, SSoC25

#1740 Implementation of Mo's Algorithm for Efficient Offline Range Queries with Multiple Query Types
  Algorithms_and_Data_Structures/Advanced Algorithms/Mos_Algorithm/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Mos_Algorithm/mos_algorithm.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1738 Implementation of Sieve of Eratosthenes Algorithm with Multiple Optimized Variants
  Algorithms_and_Data_Structures/Advanced Algorithms/Sieve_of_Eratosthenes/README.md
  Algorithms_and_Data_Structures/Advanced Algorithms/Sieve_of_Eratosthenes/sieve_of_eratosthenes.py
Labels: Contributor, Status: Review Ongoing 🔄, Intermediate, SSoC25

#1758 Add ArtForgeAI: Dataset-Free RL Brushstroke Painter
  Deep_Learning/ArtForgeAI/PROJECT_SUMMARY.md
  Deep_Learning/ArtForgeAI/README.md
  Deep_Learning/ArtForgeAI/agent.py
  Deep_Learning/ArtForgeAI/canvas.py
  Deep_Learning/ArtForgeAI/demo.py
  Deep_Learning/ArtForgeAI/quick_test.py
  Deep_Learning/ArtForgeAI/requirements.txt
  Deep_Learning/ArtForgeAI/run_tests.py
  Deep_Learning/ArtForgeAI/strokes.py
  Deep_Learning/ArtForgeAI/test_basic.py
  Deep_Learning/ArtForgeAI/tests/__init__.py
  Deep_Learning/ArtForgeAI/tests/test_agent.py
  Deep_Learning/ArtForgeAI/tests/test_canvas.py
  Deep_Learning/ArtForgeAI/tests/test_strokes.py
  Deep_Learning/ArtForgeAI/tests/test_train.py
  Deep_Learning/ArtForgeAI/train.py
  Deep_Learning/ArtForgeAI/verify_setup.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1755 Add KeyMentor: AI Keystroke Dynamics Coach and Typing Tutor
  Deep_Learning/KeyMentor/README.md
  Deep_Learning/KeyMentor/analyzer.py
  Deep_Learning/KeyMentor/exercise_generator.py
  Deep_Learning/KeyMentor/exports/typing_sessions.csv
  Deep_Learning/KeyMentor/requirements.txt
  Deep_Learning/KeyMentor/tests/test_analyzer.py
  Deep_Learning/KeyMentor/tests/test_exercise_generator.py
  Deep_Learning/KeyMentor/tests/test_tracker.py
  Deep_Learning/KeyMentor/tests/test_ui.py
  Deep_Learning/KeyMentor/tracker.py
  Deep_Learning/KeyMentor/ui.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1754 Add MazeMind: Dynamic Maze Generation, Pathfinding, and RL Agent
  Deep_Learning/MazeMind/README.md
  Deep_Learning/MazeMind/demo.py
  Deep_Learning/MazeMind/maze_generator.py
  Deep_Learning/MazeMind/pathfinding.py
  Deep_Learning/MazeMind/requirements.txt
  Deep_Learning/MazeMind/rl_agent.py
  Deep_Learning/MazeMind/simulate.py
  Deep_Learning/MazeMind/tests/__init__.py
  Deep_Learning/MazeMind/tests/test_maze_generator.py
  Deep_Learning/MazeMind/tests/test_pathfinding.py
  Deep_Learning/MazeMind/tests/test_rl_agent.py
  Deep_Learning/MazeMind/tests/test_simulate.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1753 Add SnakeRL: Reinforcement Learning Agent for the Snake Game
  Deep_Learning/SnakeRL/.gitignore
  Deep_Learning/SnakeRL/README.md
  Deep_Learning/SnakeRL/main.py
  Deep_Learning/SnakeRL/requirements.txt
  Deep_Learning/SnakeRL/src/__init__.py
  Deep_Learning/SnakeRL/src/agents/__init__.py
  Deep_Learning/SnakeRL/src/agents/base_agent.py
  Deep_Learning/SnakeRL/src/agents/dqn_agent.py
  Deep_Learning/SnakeRL/src/agents/qlearning_agent.py
  Deep_Learning/SnakeRL/src/environment/__init__.py
  Deep_Learning/SnakeRL/src/environment/snake_env.py
  Deep_Learning/SnakeRL/src/utils/__init__.py
  Deep_Learning/SnakeRL/src/utils/logger.py
  Deep_Learning/SnakeRL/src/utils/visualization.py
  Deep_Learning/SnakeRL/tests/__init__.py
  Deep_Learning/SnakeRL/tests/test_agents.py
  Deep_Learning/SnakeRL/tests/test_environment.py
  Deep_Learning/SnakeRL/tests/test_utils.py
Labels: Contributor, Status: Review Ongoing 🔄, Intermediate, SSoC25

#1752 Add ExplainDoku: Sudoku Solver with Human-Style Explanations
  Deep_Learning/ExplainDoku/LICENSE
  Deep_Learning/ExplainDoku/README.md
  Deep_Learning/ExplainDoku/debug_solver.py
  Deep_Learning/ExplainDoku/debug_test.py
  Deep_Learning/ExplainDoku/examples/easy_medium_hard.txt
  Deep_Learning/ExplainDoku/explaindoku/__init__.py
  Deep_Learning/ExplainDoku/explaindoku/core/__init__.py
  Deep_Learning/ExplainDoku/explaindoku/core/constraints.py
  Deep_Learning/ExplainDoku/explaindoku/core/grid.py
  Deep_Learning/ExplainDoku/explaindoku/core/search.py
  Deep_Learning/ExplainDoku/explaindoku/core/solver.py
  Deep_Learning/ExplainDoku/explaindoku/core/strategies/__init__.py
  Deep_Learning/ExplainDoku/explaindoku/core/strategies/fish.py
  Deep_Learning/ExplainDoku/explaindoku/core/strategies/locked_candidates.py
  Deep_Learning/ExplainDoku/explaindoku/core/strategies/pairs_triples.py
  Deep_Learning/ExplainDoku/explaindoku/core/strategies/singles.py
  Deep_Learning/ExplainDoku/explaindoku/explain/__init__.py
  Deep_Learning/ExplainDoku/explaindoku/explain/templates.py
  Deep_Learning/ExplainDoku/explaindoku/explain/trace.py
  Deep_Learning/ExplainDoku/explaindoku/explain/verbalizer.py
  Deep_Learning/ExplainDoku/explaindoku/ui/__init__.py
  Deep_Learning/ExplainDoku/explaindoku/ui/cli.py
  Deep_Learning/ExplainDoku/explaindoku/ui/streamlit_app.py
  Deep_Learning/ExplainDoku/requirements.txt
  Deep_Learning/ExplainDoku/run_tests.py
  Deep_Learning/ExplainDoku/tests/__init__.py
  Deep_Learning/ExplainDoku/tests/test_grid.py
  Deep_Learning/ExplainDoku/tests/test_solver.py
  Deep_Learning/ExplainDoku/tests/test_strategies.py
Labels: Contributor, Status: Review Ongoing 🔄, Advanced, SSoC25

#1777 Fixed Issue #1733: Added logistic-regression code to the ML folder.
  Machine_Learning/Logistic-Regression/README.md
  Machine_Learning/Logistic-Regression/logistic_regression.ipynb
Labels: Contributor, Status: Review Ongoing 🔄, level1, gssoc25

#1778 Added Web App
  Deep_Learning/Crop Production/artifacts/my_model (1).keras
  Deep_Learning/Crop Production/artifacts/preprocessor (1).pkl
  Deep_Learning/Crop Production/artifacts/y_scaler (2).pkl
  Deep_Learning/Crop Production/crop_production.ipynb
  Deep_Learning/Crop Production/image.png
  Deep_Learning/Crop Production/page.py
  Deep_Learning/Crop Production/readme.md
  Deep_Learning/Crop Production/requirements.txt
Labels: Contributor, Status: Review Ongoing 🔄, level2, gssoc25
